### ISSUE TITLE
magick error

### ISSUE THREAD

**Issue by ebarry** [developmentseed/landsat-util#10]
After updating Xcode to 4.6.3 and running brew doctor, still i get this error after running 
the install for landsat-util--has anyone seen this before?

1 error generated.
make[1]: *** [magick/magick_libMagickCore_6_Q16_la-annotate.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

**Comment by scisco** [comment]
Imagemagick is not longer used in the new version of landsat-util. closing.
