### ISSUE TITLE
Support for Copernicus Sentinel-2 imaginery

### ISSUE THREAD

**Issue by JorgeGT** [developmentseed/landsat-util#107]
This is just a far fetched open question: would be interesting to support the download / processing of imaginery from the Sentinel-2 satellites of the Copernicus mission? A few points of interest:

### The mission

>Multi-spectral data with 13 bands in the visible, near infrared, and short wave infrared part of the spectrum
>Systematic global coverage of land surfaces from 56° S to 84° N, coastal waters, and all of the Mediterranean Sea
>Revisiting every 5 days at the Equator under the same viewing conditions
>Spatial resolution of 10 m, 20 m and 60 m
>290 km field of view
>Free and open data policy

### Imaginery

Among others, there will be 4 bands at 10m resolution (50% more than Landsat-8): red, green, blue and VNIR. Nicely, there is no need to pansharpen in order to get images at max. resolution.

![bands](http://www.cesbio.ups-tlse.fr/data_all/images/sentinel1.png)

### Data access 

Data will be free to access. The good news are that there is an API to perform searches (including geographical bounding, cloud cover, date, etc.) and download quicklooks and products. This API is well documented [here](https://scihub.esa.int/userguide/BatchScripting). The bad news are that the API requires user registration:

```bash
curl -u username:password "https://scihub.esa.int/dhus/search?q=S2A*&format=json"
```

Also, the images are distributed in a specific SAFE format which I'm not sure GDAL supports yet (it seems that GDAL [supports Sentinel-1 SAFE](http://www.gdal.org/frmt_safe.html), but not Sentinel-2 SAFE).

---

As you can see the tools are not so ready yet, but I think it could be interesting to have this issue in mind in order to someday extend the functionality of landsat-util, no? The possibility of **50% higher** resolution imaginary with **1/3** of the revisit time **without** the need of pansharpening (which highly increases the resources needed) is very tempting!

What do you think? =)

**Comment by jflasher** [comment]
@JorgeGT this is definitely something we're interested in and are actively exploring! We'd probably not make it part of landsat-util but would instead create a wrapper library like sat-util that could have other libs like landsat-util and sentinel2-util included within it, but that'll be something we need to decided once we start development. 

Quick question for you if you've been looking at the data sources, when I looked previously, it seemed like the API only gave results going back a month or so. Did you find this as well or does it look like it's giving full historic data access?

**Comment by JorgeGT** [comment]
@jflasher I think it's giving full access to historic data, I just tried this:

```sh
wget --no-check-certificate --user=XXX --password=XXXX -qO- "https://scihub.esa.int/dhus/search?q=ingestionDate:[NOW-6MONTH TO NOW-5MONTH]&format=json" | grep \"Date: | sort -t: -n -k3
```

And I got:

```
"summary": "Date: 2015-03-31T21:38:16.493Z, Instrument: SAR-C SAR, Mode: VH VV, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-03-31T21:38:41.494Z, Instrument: SAR-C SAR, Mode: VH VV, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-03-31T21:39:06.493Z, Instrument: SAR-C SAR, Mode: VH VV, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-03-31T21:39:31.493Z, Instrument: SAR-C SAR, Mode: VH VV, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-04-01T18:25:21.413Z, Instrument: SAR-C SAR, Mode: VV VH, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-04-01T18:25:46.413Z, Instrument: SAR-C SAR, Mode: VV VH, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-04-01T18:26:11.413Z, Instrument: SAR-C SAR, Mode: VV VH, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-04-01T18:26:36.414Z, Instrument: SAR-C SAR, Mode: VV VH, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-04-01T18:27:01.414Z, Instrument: SAR-C SAR, Mode: VV VH, Satellite: Sentinel-1, Size: 1 GB",
"summary": "Date: 2015-04-01T18:27:26.412Z, Instrument: SAR-C SAR, Mode: VV VH, Satellite: Sentinel-1, Size: 1 GB",
```

If I try a full search `https://scihub.esa.int/dhus/search?q=*&format=json` I get 240449 results, and the older one is:

```
"summary": "Date: 2014-12-05T06:02:19.264Z, Instrument: SAR-C SAR, Mode: VV VH, Satellite: Sentinel-1, Size: 1 GB",
```

**Comment by jflasher** [comment]
@JorgeGT Interesting! Thanks for looking into this more.

**Comment by ramotswa** [comment]
+1 from me for this - and this might be of interest to make things easier for you too! :) 

http://sentinel-pds.s3-website.eu-central-1.amazonaws.com/

Looking forward to it!

**Comment by JorgeGT** [comment]
@ramotswa That's very nice of Amazon, now there's no need to register with ESA!

**Comment by ramotswa** [comment]
Yes very nice indeed. Credit where it is due; Sinergise is behind the
ingestion of s2 to AWS. (https://github.com/sinergise). Also as far as I
can see they don't expose a search API.

I have taken a fork of the Landsat-utils and have made some very rough
modifications towards making it work with S2 data.

Things to change for the processing side of things.

S2 data comes In jp2 format. Does rasterio support jp2? If it needs
proprietary SDK's (hexagon stuff) then that's not a great.
Folder structure: s2 data comes split into 9(I think) granules, each with
12 bands. So it'll need a bit of a loop to go though each granule folder.
Also Band file names have a 0 before the band number (_B04.jp2)
Pansharpen: no need for this.
Cloud / snow masks: each granule has a cloud mask in gml format. If I
understand the code correctly: for Landsat you count the pixels of certain
values and use that to figure out the proportion of clouds for processing
purposes. For s2 The gml could just be used to find the area of all the
geometries and then divide by 10 in order to get pixel count. Just thinking
out loud really.

That's all I can think of for now. For search we'll still need the ESA Api.
For download it should just be a case of changing the download url.

Any pointers welcome.
T

**Comment by scisco** [comment]
We working on this and should have a sentinel-util soon.

**Comment by JorgeGT** [comment]
That's great to hear @scisco :)

**Comment by ramotswa** [comment]
Out of interest, will this cover only sentinel 2? Or are you looking to
include sentinel 1 and 3 (at some point) as well?

**Comment by scisco** [comment]
@ramotswa it will only cover sentinel2 at this point
