### ISSUE TITLE
Command not found. Installation or working directory error?

### ISSUE THREAD

**Issue by dsconstable** [developmentseed/landsat-util#108]
Installed landsat util 0.7.0 on a mac running 10.10.4 via: ```sudo easy_install pip``` and ```pip install landsat-util```. Installation seems to have worked, but trying to run any command in terminal results in the message "command not found". Has anyone run into this and know off hand what the issue might be, e.g. command syntax or an installation issue?

```
ABC: landsat-util-0.7.0 develop$ landsat -h
-bash: landsat: command not found
```

**Comment by scisco** [comment]
Installation steps are documented here: https://pythonhosted.org/landsat-util/installation.html
