### ISSUE TITLE
nothing available

### ISSUE THREAD

**Issue by RoboDonut** [developmentseed/landsat-util#109]
no scenes seems to be available even the ones in the examples can't be downloaded

``` 
>>> dwner.download(['LC80090452015008LGN00'],['5','4','3','2'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\ArcGIS10.3\lib\site-packages\landsat\downloader.py", line 68, in download
    self.google_storage(scene, self.download_dir)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\landsat\downloader.py", line 107, in google_storage
    raise RemoteFileDoesntExist('%s is not available on Google Storage' % filename)
landsat.downloader.RemoteFileDoesntExist: LC80090452015008LGN00.tar.bz is not available on Google Storage
```

additionally when i specify the bands it seems to still be looking at google for the download.

**Comment by RoboDonut** [comment]
these seems to be a windows issue pertaining to the URL joining. 

when digging in deeper to see why it cant download files i search for i started to look at
``` downloader.amazon_s3_url()```
and when i build out the scene object and specify the scene like
``` dwner.amazon_s3_url(scene_obj,'LC82050302015216LGN00_B1.TIF') ```
i get
```'http://landsat-pds.s3.amazonaws.com/L8\\205\\030\\LC82050302015216LGN00\\LC82050302015216LGN00_B1.TIF' ```
returned  to me which obviously wont work

but
``` http://landsat-pds.s3.amazonaws.com/L8/205/030/LC82050302015216LGN00/LC82050302015216LGN00_B1.TIF ```

i think the issue is with the os.path.join on windows vs linux

**Comment by RoboDonut** [comment]
This is an issue with URL joining in the google and amazon URL function. python ` join ` on nix systems v. windows systems is the root issue. suggest replacing with ` '/'.join([]) ` . fixing on my fork. will submit a pull request.

**Comment by jacquestardie** [comment]
:+1: @RoboDonut
