### ISSUE TITLE
Inconsistency detected by ld.so under Ubuntu 14.04 

### ISSUE THREAD

**Issue by northrivergeo** [developmentseed/landsat-util#11]
New one - lets see how this works in the copying and pasting: 

landsat process --pansharpen ./zip/LC80200362014197LGN00.tar.bz
/tmp/tmptn_r7_/LC80200362014197LGN00 folder created
/tmp/tmptn_r7_/LC80200362014197LGN00/warp folder created
/tmp/tmptn_r7_/LC80200362014197LGN00/scaled folder created
/tmp/tmptn_r7_/LC80200362014197LGN00/final folder created
Unzipping LC80200362014197LGN00 - It might take some time
Creating output file that is 7720P x 7893L.
Processing input file /tmp/tmptn_r7_/LC80200362014197LGN00/LC80200362014197LGN00_B4.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7720P x 7893L.
Processing input file /tmp/tmptn_r7_/LC80200362014197LGN00/LC80200362014197LGN00_B3.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7720P x 7893L.
Processing input file /tmp/tmptn_r7_/LC80200362014197LGN00/LC80200362014197LGN00_B2.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 15439P x 15786L.
Processing input file /tmp/tmptn_r7_/LC80200362014197LGN00/LC80200362014197LGN00_B8.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Starting the Min/Max process with designated -percent cut- for band 4 of LC80200362014197LGN00
...
Finished processing band 4 of LC80200362014197LGN00
Starting the Min/Max process with designated -percent cut- for band 3 of LC80200362014197LGN00
...
Finished processing band 3 of LC80200362014197LGN00
Starting the Min/Max process with designated -percent cut- for band 2 of LC80200362014197LGN00
...
Finished processing band 2 of LC80200362014197LGN00
scaling pan to min max with 2% cut for band 4
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
scaling pan to min max with 2% cut for band 3
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
scaling pan to min max with 2% cut for band 2
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
/tmp/tmptn_r7_/LC80200362014197LGN00/warp/LC80200362014197LGN00_B4.TIF[0] TIFF 7720x7893 7720x7893+0+0 16-bit Grayscale DirectClass 121.9MB 0.500u 0:00.570
/tmp/tmptn_r7_/LC80200362014197LGN00/warp/LC80200362014197LGN00_B3.TIF[0] TIFF 7720x7893 7720x7893+0+0 16-bit Grayscale DirectClass 121.9MB 0.330u 0:00.359
/tmp/tmptn_r7_/LC80200362014197LGN00/warp/LC80200362014197LGN00_B2.TIF[0] TIFF 7720x7893 7720x7893+0+0 16-bit Grayscale DirectClass 121.9MB 0.170u 0:00.190
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
/tmp/tmptn_r7_/LC80200362014197LGN00/scaled/LC80200362014197LGN00_B4.TIF[0] TIFF 7720x7893 7720x7893+0+0 8-bit Grayscale DirectClass 61MB 0.500u 0:00.530
/tmp/tmptn_r7_/LC80200362014197LGN00/scaled/LC80200362014197LGN00_B3.TIF[0] TIFF 7720x7893 7720x7893+0+0 8-bit Grayscale DirectClass 61MB 0.330u 0:00.339
/tmp/tmptn_r7_/LC80200362014197LGN00/scaled/LC80200362014197LGN00_B2.TIF[0] TIFF 7720x7893 7720x7893+0+0 8-bit Grayscale DirectClass 61MB 0.170u 0:00.170
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
Starting the image processing
global name 'cv2' is not defined
Skipping Image Correction using OpenCV
Convertin image tweaks
Convert: averaging
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
convert.im6: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
World file written to '/tmp/tmptn_r7_/LC80200362014197LGN00/warp/LC80200362014197LGN00_B4.tfw'.

2014 Sep 02 18:22:42  :  Application.logger  (INFO) Elevation management: setting default height above ellipsoid to  0 meters
Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 0% [             Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 2% [\*            Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 4% [*\*           Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 6% [**\*          Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 8% [***\*         Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 10% [****\*       Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 12% [*****\*      Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 14% [******\*     Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 16% [*******\*    Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 18% [********\*   Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 20% [*********\*  Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 22% [**********\* Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 24% [************Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 26% [************Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 28% [************Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 30% [************Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 32% [************Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 34% [****************\*                         Writing /tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF...: 100% [**************************************************](1e+02 seconds)
Inconsistency detected by ld.so: dl-close.c: 762: _dl_close: Assertion `map->l_init_called' failed!
subprocess.CalledProcessError: Command '['otbcli_BundleToPerfectSensor', '-inp', '/tmp/tmptn_r7_/LC80200362014197LGN00/warp/LC80200362014197LGN00_B8.TIF', '-inxs', '/tmp/tmptn_r7_/LC80200362014197LGN00/final/comp.TIF', '-out', '/tmp/tmptn_r7_/LC80200362014197LGN00/final/pan.TIF', 'uint16']' returned non-zero exit status 127

**Comment by oeon** [comment]
@scisco so does `otb-bin` need to be included in the Ubuntu instructions https://github.com/developmentseed/landsat-util/blame/master/README.rst#L37? I was getting a similar error (also 14.04) but resolved after installing it.

**Comment by scisco** [comment]
@oeon It is certainly an error that I didn't get in my tests a few months ago. We are updating the requirements and installation process for the next version of landsat-util. I will certainly test it against this ticket and will let you know.
