### ISSUE TITLE
NDVI processing

### ISSUE THREAD

**Issue by akudrya** [developmentseed/landsat-util#110]
Hi guys,

I wonder is it possible to process NDVI similar to Astro Digital server processing?

I've updated to 0.7.0 version and tried:
```landsat process LC81730242014085LGN00.tar.bz --ndvi```

The util responded:
```landsat: error: unrecognized arguments: --ndvi ```

**Comment by JorgeGT** [comment]
I believe NDVI support was commited to the develop branch after the 0.7.0 release, so you must download/clone the develop branch and manually install it.

**Comment by scisco** [comment]
@akudrya latest version of landsat-util is pushed to pypi. Try `pip install -U landsat-util`
