### ISSUE TITLE
download command only downloading RGB bands

### ISSUE THREAD

**Issue by stml** [developmentseed/landsat-util#130]
Unsure if this is a bug, but landsat-util does not seem to be behaving as expected from the documentation.

The standard download command only downloads Bands 4,3,2 (the visible bands) and the QA band. In the docs it says it should be downloading a zip file of all bands. This is the output:

    (venv)XXXXXX:landsat XXXXX$ landsat download LC81720352015321LGN00
    ===> Downloading: LC81720352015321LGN00_B4.TIF
       100%     65.1 MiB     374.9 KiB/s            0:00:00 ETA     
         stored at /Users/XXXX/landsat/downloads/LC81720352015321LGN00    
    ===> Downloading: LC81720352015321LGN00_B3.TIF
       100%     64.5 MiB     348.1 KiB/s            0:00:00 ETA    
         stored at /Users/XXXX/landsat/downloads/LC81720352015321LGN00
    ===> Downloading: LC81720352015321LGN00_B2.TIF
       100%     64.3 MiB     490.8 KiB/s            0:00:00 ETA    
         stored at /Users/XXXX/landsat/downloads/LC81720352015321LGN00
    ===> Downloading: LC81720352015321LGN00_BQA.TIF
       100%      2.7 MiB     563.9 KiB/s            0:00:00 ETA    
         stored at /Users/XXXX/landsat/downloads/LC81720352015321LGN00
    ===> Downloading: LC81720352015321LGN00_MTL.txt
       100%      7.4 KiB       7.4 KiB/s            0:00:00 ETA    
         stored at /Users/XXXX/landsat/downloads/LC81720352015321LGN00
    ===> Download Completed
    ===> Done!
    Time spent : 523.64 seconds

I can download other bands, e.g.:

    (venv)Otago-2:landsat james$ landsat download LC81810332015288LGN00 --band 5678
    ===> Downloading: LC81810332015288LGN00_B5.TIF
    etc

But this is obviously much slower than downloading a zip file when I want all the layers, as the docs suggest I should be able to get. (The docs also specify a --bands rather than -band flag, which throws an error.)

**Comment by scisco** [comment]
fixed here: https://github.com/developmentseed/landsat-util/pull/135

**Comment by stml** [comment]
Amazing, thanks!
