### ISSUE TITLE
installation error on os x 10.11

### ISSUE THREAD

**Issue by aaschwanden** [developmentseed/landsat-util#131]
Hi, 

I'm trying to install landsat-util on my os x 10.11 and macports python.

    $ sudo python setup.py install

ends with the following complaint:

creating /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/landsat_util-0.9.1-py2.7.egg
Extracting landsat_util-0.9.1-py2.7.egg to /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
landsat-util 0.9.1 is already the active version in easy-install.pth
Installing landsat script to /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin

Installed /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/landsat_util-0.9.1-py2.7.egg
Processing dependencies for landsat-util==0.9.1
error: six 1.9.0 is installed but six==1.8.0 is required by set(['polyline'])

I can't quite figure out where the ```six==1.8.0 is required by set(['polyline'])``` is coming from.

Thanks,

Andy

**Comment by scisco** [comment]
@aaschwanden could you try the installation inside a [virtualenv](http://sourabhbajaj.com/mac-setup/Python/virtualenv.html)?
