### ISSUE TITLE
Extend search tool to older Landsat ETM, TM imagery?

### ISSUE THREAD

**Issue by steflhermitte** [developmentseed/landsat-util#133]
Dear,

First I would like to thank you for the wonderful tool! Secondly, I wondered if you consider extending the search function to also allow searching within the Landsat 4-7 archives? For example, by adding the metadata of these images to the Development Seed’s API for Landsat Metadata and by adding a --sensor flag. 

The download tool already works for these older images as, but I still have to query them using the USGS online search tool.

Thanks again,
Stef

**Comment by drewbo** [comment]
Noting https://landsat.usgs.gov/download-entire-collection-metadata as a potential source for this enhancement

**Comment by matthewhanson** [comment]
@steflhermitte While we making some minor updates to landsat-util it will be deprecated in favor of using our new [sat-api](https://medium.com/devseed/sat-api-an-api-for-spatiotemporal-asset-catalogs-88c3c78fdb0e) and [sat-search](https://github.com/sat-utils/sat-search/).

We hope to be able to add support for older Landsats in sat-api at some point.
