### ISSUE TITLE
Search command seems to be doing nothing

### ISSUE THREAD

**Issue by negroscuro** [developmentseed/landsat-util#137]
Hello,
I recently installed landsat util v0.10b3 having python 2.7.6 in Ubuntu 14.04.3 LTS by doing this:

sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt-get install --yes python-pip python-skimage python-numpy python-scipy libgdal-dev libatlas-base-dev gfortran libfreetype6-dev libglib2.0-dev zlib1g-dev python-pycurl git build-essential libssl-dev libffi-dev python-dev python-gdal libgdal1-dev gdal-bin imagemagick geotiff-bin -y
sudo -H pip install -U pip
sudo -H pip install -U git+git://github.com/developmentseed/landsat-util.git
sudo -H pip install --no-deps git+git://github.com/developmentseed/landsat-util.git
sudo -H pip install requests[security]

after that I tried to run examples from the landsatutil website:
landsat search --cloud 4 --start "january 1 2014" --end "january 10 2014" -p 009,045
and
landsat search --lat 38.9004204 --lon -77.0237117

but i got no error or nothing done... so i dont know what is happening... but the command is there and I was able to run a landsat download command (landsat download LC80090452014008LGN00)

Anybody had the same problem?
thank you in advance.

**Comment by negroscuro** [comment]
I have python 2.7.6 in a Ubuntu 14.04.3 LTS

**Comment by negroscuro** [comment]
When I used landsat utils web page installation process:

$: sudo apt-get update
$: sudo apt-get install python-pip python-numpy python-scipy libgdal-dev libatlas-base-dev gfortran libfreetype6-dev
$: pip install landsat-util


I got the following error:
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_negro/landsat-util/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_XkuSc-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_negro/landsat-util

**Comment by scisco** [comment]
If you have docker, using [the docker image](https://pythonhosted.org/landsat-util/installation.html#docker) would be a bit faster and easier. Anyhow, these are the steps to install landsat-util on a blank Ubuntu 14.04 on docker [from here](https://github.com/developmentseed/landsat-util/blob/develop/Dockerfile) with few edits for a non docker environment.

```
sudo apt-get update
sudo apt-get install python-pip python-skimage python-numpy python-scipy libgdal-dev libatlas-base-dev gfortran libfreetype6-dev libglib2.0-dev zlib1g-dev python-pycurl
git clone https://github.com/developmentseed/landsat-util.git landsat
sudo cp -r landsat /usr/local/lib/python.27/dist-packages/landsat
sudo cp landsat/bin/landsat /usr/local/bin/
cd landsat
sudo pip install -r requirements/docker.txt
```

**Comment by dkerkow** [comment]
Same problem here. Using docker is not an option for me at the moment. Could it be an issue with urllib3 and SSL? Because I get InsecurePlatform warnings when running version 0.9.1.

**Comment by negroscuro** [comment]
@scisco: I ran the sentences you said but I still have the same... unusual behavior, I run
landsat search --lat 38.9004204 --lon -77.0237117
And there is no result, no error.... nothing.

Do you know how to get a previous version of LandsatTools?

**Comment by scisco** [comment]
@negroscuro thanks for catching this. I fixed the bug and pushing out a new version now.

Also, to install an older version you can run `pip install landsat-util==0.9.0`. Just replace the number with the version you need. The list of all versions is here: https://github.com/developmentseed/landsat-util/releases

**Comment by negroscuro** [comment]
Thank you so much for your support I think now is working!
