### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by marcellobenigno** [developmentseed/landsat-util#14]
when i try to render the image of the manual, the following error occurs:

marcello@ubuntu:SEM → landsat process --pansharpen LC80090452014008LGN00.tar.bz
/tmp/tmpEJwZXS/LC80090452014008LGN00 folder created
/tmp/tmpEJwZXS/LC80090452014008LGN00/warp folder created
/tmp/tmpEJwZXS/LC80090452014008LGN00/scaled folder created
/tmp/tmpEJwZXS/LC80090452014008LGN00/final folder created
/home/marcello/landsat/processed/LC80090452014008LGN00 folder created
Unzipping LC80090452014008LGN00 - It might take some time
Creating output file that is 7657P x 7857L.
Processing input file /tmp/tmpEJwZXS/LC80090452014008LGN00/LC80090452014008LGN00_B4.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7657P x 7857L.
Processing input file /tmp/tmpEJwZXS/LC80090452014008LGN00/LC80090452014008LGN00_B3.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7657P x 7857L.
Processing input file /tmp/tmpEJwZXS/LC80090452014008LGN00/LC80090452014008LGN00_B2.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 15312P x 15712L.
Processing input file /tmp/tmpEJwZXS/LC80090452014008LGN00/LC80090452014008LGN00_B8.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Starting the Min/Max process with designated -percent cut- for band 4 of LC80090452014008LGN00
...
Finished processing band 4 of LC80090452014008LGN00
Starting the Min/Max process with designated -percent cut- for band 3 of LC80090452014008LGN00
...
Finished processing band 3 of LC80090452014008LGN00
Starting the Min/Max process with designated -percent cut- for band 2 of LC80090452014008LGN00
...
Finished processing band 2 of LC80090452014008LGN00
scaling pan to min max with 2% cut for band 4
OSError: [Errno 12] Cannot allocate memory

My machine has 8 gb of RAM and I believe this can be a problem in Python

**Comment by scisco** [comment]
Activating swappable is the answer. Closing..
