### ISSUE TITLE
Downloading and proccessing bands error

### ISSUE THREAD

**Issue by negroscuro** [developmentseed/landsat-util#144]
Hello,
I am running this

landsat download LC82020322015275LGN00 --bands 1110987654321 --process
or
landsat download  LC82010342015364LGN00 -b 1110987654321 -p

But it always result in all bands getting downloaded correctly as expected but when reprojecting:

===> Image processing started for bands 11-10-9-8-7-6-5-4-3-2-1
===> Getting boundaries
===> Projecting
     band 11
     band 10
     band 9
     band 8
Time spent : 36.90 seconds
Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 475, in __main__
    exit(*main(args))
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 402, in main
    args.ndvigrey, bounds=bounds)
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 463, in process_image
    return p.run()
  File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 403, in run
    self._warp(image_data, bands, new_bands)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 155, in _warp
    reproject(band, new_bands[i], src_transform=proj_data['transform'], src_crs=proj_data['crs'],
IndexError: list index out of range

I dont know if I am doing anything wrong or if it is the landsat util tool... can anybody help me with this?
Thank you in advance.
Mario.

**Comment by scisco** [comment]
I think the problem is that you are specifying all the bands for processing. Landsat-util cannot process more than three bands. What kind of image you need to produce? Try the same command like this and let me know if it works:

    landsat download LC82010342015364LGN00 -b 432 -p

**Comment by negroscuro** [comment]
I ran 
landsat download LC82010342015364LGN00 -b 432 -p

And I got

===> Downloading: LC82010342015364LGN00_B4.TIF
   100%     60.8 MiB       5.8 MiB/s            0:00:00 ETA
     stored at /home/atos/landsat/downloads/LC82010342015364LGN00
===> Downloading: LC82010342015364LGN00_B3.TIF
   100%     58.9 MiB       7.1 MiB/s            0:00:00 ETA
     stored at /home/atos/landsat/downloads/LC82010342015364LGN00
===> Downloading: LC82010342015364LGN00_B2.TIF
   100%     56.6 MiB       5.9 MiB/s            0:00:00 ETA
     stored at /home/atos/landsat/downloads/LC82010342015364LGN00
===> Downloading: LC82010342015364LGN00_BQA.TIF
   100%      4.7 MiB     909.7 KiB/s            0:00:00 ETA
     stored at /home/atos/landsat/downloads/LC82010342015364LGN00
===> Downloading: LC82010342015364LGN00_MTL.txt
   100%      7.7 KiB       7.7 KiB/s            0:00:00 ETA
     stored at /home/atos/landsat/downloads/LC82010342015364LGN00
===> Image processing started for bands 4-3-2
===> Getting boundaries
===> Projecting
     band 4
     band 3
     band 2
===> Calculating cloud and snow coverage from QA band
     cloud/snow coverage: 3.69
===> Final Steps
Time spent : 53.84 seconds
Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 475, in __main__
    exit(*main(args))
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 402, in main
    args.ndvigrey, bounds=bounds)
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 463, in process_image
    return p.run()
  File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 420, in run
    return self._write_to_file(new_bands, **rasterio_options)
  File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 257, in _write_to_file
    output = rasterio.open(output_file, 'w', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rasterio/__init__.py", line 123, in open
    s.start()
  File "rasterio/_io.pyx", line 1341, in rasterio._io.RasterUpdater.start (rasterio/_io.c:18967)
ValueError: NULL dataset
atos@foodie6:~$ ===> Downloading: LC82010342015364LGN00_B4.TIF
===: command not found
atos@foodie6:~$      LC82010342015364LGN00_B4.TIF already exists on your system
LC82010342015364LGN00_B4.TIF: command not found
atos@foodie6:~$ ===> Downloading: LC82010342015364LGN00_B3.TIF
===: command not found
atos@foodie6:~$      LC82010342015364LGN00_B3.TIF already exists on your system
LC82010342015364LGN00_B3.TIF: command not found
atos@foodie6:~$ ===> Downloading: LC82010342015364LGN00_B2.TIF
===: command not found
atos@foodie6:~$      LC82010342015364LGN00_B2.TIF already exists on your system
LC82010342015364LGN00_B2.TIF: command not found
atos@foodie6:~$ ===> Downloading: LC82010342015364LGN00_BQA.TIF
===: command not found
atos@foodie6:~$      LC82010342015364LGN00_BQA.TIF already exists on your system
LC82010342015364LGN00_BQA.TIF: command not found
atos@foodie6:~$ ===> Downloading: LC82010342015364LGN00_MTL.txt
===: command not found
atos@foodie6:~$      LC82010342015364LGN00_MTL.txt already exists on your system
LC82010342015364LGN00_MTL.txt: command not found
atos@foodie6:~$ ===> Image processing started for bands 4-3-2
===: command not found
atos@foodie6:~$ ===> Getting boundaries
===: command not found
atos@foodie6:~$ ===> Projecting
===: command not found
atos@foodie6:~$      band 4
No command 'band' found, did you mean:
 Command 'rand' from package 'rand' (universe)
 Command 'and' from package 'and' (universe)
 Command 'pand' from package 'bluez-compat' (universe)
 Command 'bnd' from package 'bnd' (universe)
 Command 'bang' from package 'slapos-node-unofficial' (universe)
band: command not found
atos@foodie6:~$      band 3
No command 'band' found, did you mean:
 Command 'bang' from package 'slapos-node-unofficial' (universe)
 Command 'pand' from package 'bluez-compat' (universe)
 Command 'bnd' from package 'bnd' (universe)
 Command 'rand' from package 'rand' (universe)
 Command 'and' from package 'and' (universe)
band: command not found
atos@foodie6:~$      band 2
No command 'band' found, did you mean:
 Command 'pand' from package 'bluez-compat' (universe)
 Command 'bnd' from package 'bnd' (universe)
 Command 'bang' from package 'slapos-node-unofficial' (universe)
 Command 'and' from package 'and' (universe)
 Command 'rand' from package 'rand' (universe)
band: command not found
atos@foodie6:~$ ===> Calculating cloud and snow coverage from QA band
===: command not found
atos@foodie6:~$      cloud/snow coverage: 3.69
-bash: cloud/snow: No such file or directory
atos@foodie6:~$ ===> Final Steps
===: command not found
atos@foodie6:~$ Time spent : 23.63 seconds
No command 'Time' found, did you mean:
 Command 'hime' from package 'hime' (universe)
 Command 'time' from package 'time' (main)
Time: command not found
atos@foodie6:~$ Traceback (most recent call last):
-bash: syntax error near unexpected token `most'
atos@foodie6:~$   File "/usr/local/bin/landsat", line 8, in <module>
-bash: syntax error near unexpected token `newline'
atos@foodie6:~$     landsat.landsat.__main__()
>   File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 475, in __main__
-bash: syntax error near unexpected token `File'
atos@foodie6:~$     exit(*main(args))
-bash: syntax error near unexpected token `*main'
atos@foodie6:~$   File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 402, in main
No command 'File' found, did you mean:
 Command 'zile' from package 'zile' (universe)
 Command 'file' from package 'file' (main)
 Command 'vile' from package 'vile' (universe)
 Command 'kile' from package 'kile' (universe)
File: command not found
atos@foodie6:~$     args.ndvigrey, bounds=bounds)
-bash: syntax error near unexpected token `)'
atos@foodie6:~$   File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 463, in process_image
No command 'File' found, did you mean:
 Command 'vile' from package 'vile' (universe)
 Command 'zile' from package 'zile' (universe)
 Command 'file' from package 'file' (main)
 Command 'kile' from package 'kile' (universe)
File: command not found
atos@foodie6:~$     return p.run()
-bash: syntax error near unexpected token `('
atos@foodie6:~$   File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
No command 'File' found, did you mean:
 Command 'vile' from package 'vile' (universe)
 Command 'kile' from package 'kile' (universe)
 Command 'zile' from package 'zile' (universe)
 Command 'file' from package 'file' (main)
File: command not found
atos@foodie6:~$     return func(*args, **kwargs)
-bash: syntax error near unexpected token `('
atos@foodie6:~$   File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 420, in run
No command 'File' found, did you mean:
 Command 'vile' from package 'vile' (universe)
 Command 'file' from package 'file' (main)
 Command 'zile' from package 'zile' (universe)
 Command 'kile' from package 'kile' (universe)
File: command not found
atos@foodie6:~$     return self._write_to_file(new_bands, **rasterio_options)
-bash: syntax error near unexpected token `('
atos@foodie6:~$   File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
No command 'File' found, did you mean:
 Command 'kile' from package 'kile' (universe)
 Command 'file' from package 'file' (main)
 Command 'vile' from package 'vile' (universe)
 Command 'zile' from package 'zile' (universe)
File: command not found
atos@foodie6:~$     return func(*args, **kwargs)
-bash: syntax error near unexpected token `('
atos@foodie6:~$   File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 257, in _write_to_file
No command 'File' found, did you mean:
 Command 'vile' from package 'vile' (universe)
 Command 'kile' from package 'kile' (universe)
 Command 'zile' from package 'zile' (universe)
 Command 'file' from package 'file' (main)
File: command not found
atos@foodie6:~$     output = rasterio.open(output_file, 'w', **kwargs)
-bash: syntax error near unexpected token `('
atos@foodie6:~$   File "/usr/local/lib/python2.7/dist-packages/rasterio/__init__.py", line 123, in open
No command 'File' found, did you mean:
 Command 'zile' from package 'zile' (universe)
 Command 'file' from package 'file' (main)
 Command 'vile' from package 'vile' (universe)
 Command 'kile' from package 'kile' (universe)
File: command not found
atos@foodie6:~$     s.start()
>   File "rasterio/_io.pyx", line 1341, in rasterio._io.RasterUpdater.start (rasterio/_io.c:18967)
-bash: syntax error near unexpected token `File'
atos@foodie6:~$ ValueError: NULL dataset
ValueError:: command not found

**Comment by negroscuro** [comment]
I tried to process bands in groups and it seems processing band 11 and 10 gave me the error


===> Image processing started for bands 11-10
===> Getting boundaries
===> Projecting
     band 11
     band 10
===> Calculating cloud and snow coverage from QA band
     cloud/snow coverage: 3.69
===> Final Steps
     Color correcting band 11
Time spent : 12.60 seconds
Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 475, in __main__
    exit(*main(args))
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 290, in main
    args.ndvigrey, bounds)
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 463, in process_image
    return p.run()
  File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 420, in run
    return self._write_to_file(new_bands, **rasterio_options)
  File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 261, in _write_to_file
    band = self._color_correction(band, self.bands[i], 0, coverage)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 272, in _color_correction
    p_low, cloud_cut_low = self._percent_cut(band, low, 100 - (coverage * 3 / 4))
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 281, in _percent_cut
    return numpy.percentile(color[numpy.logical_and(color > 0, color < 65535)], (low, high))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 3268, in percentile
    interpolation=interpolation)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 2997, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 3385, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 124, in take
    return take(indices, axis, out, mode)
IndexError: cannot do a non-empty take from an empty axes.



That makes sense?

**Comment by negroscuro** [comment]
Now i am running:

landsat process LC82010342015364LGN00 --bands 432 --pansharpen

And I get:

Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 475, in __main__
    exit(*main(args))
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 290, in main
    args.ndvigrey, bounds)
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 463, in process_image
    return p.run()
  File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 474, in run
    return self._write_to_file(new_bands, pan, **rasterio_options)
  File "/usr/local/lib/python2.7/dist-packages/landsat/decorators.py", line 10, in wrapped_f
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 493, in _write_to_file
    band = self._color_correction(band, self.bands[i], 0, coverage)
  File "/usr/local/lib/python2.7/dist-packages/landsat/image.py", line 276, in _color_correction
    temp[mask] = rescale_intensity(band[mask], in_range=(p_low, cloud_cut_low), out_range=(256, cloud_divide))
  File "/usr/local/lib/python2.7/dist-packages/skimage/exposure/exposure.py", line 307, in rescale_intensity
    image = (image - imin) / float(imax - imin)

**Comment by negroscuro** [comment]
For some reason if i remove the pansharppen parameter it works without any error.

**Comment by negroscuro** [comment]
It works.
