### ISSUE TITLE
Commandline parsing fails when --clip parameters start with a negative value

### ISSUE THREAD

**Issue by dkerkow** [developmentseed/landsat-util#147]
To reproduce it, try the following: 

```bash
landsat download LC82190322014151LGN00 -p --pansharpen --clip -30.6678274778,39.7258925095,-30.6278274778,39.7658925095 -d gis/landsat
```
Remove the "-" before the first value and it works:

```bash
landsat download LC82190322014151LGN00 -p --pansharpen --clip 30.6678274778,39.7258925095,-30.6278274778,39.7658925095 -d gis/landsat
```

The bug is also triggered when you put it in quotes.

Version is 0.11.0

**Comment by dkerkow** [comment]
Ok, using the `--clip=` Syntax works. So maybe it should be updated accordingly in the docs.

**Comment by scisco** [comment]
@dkerkow it should also work if you put the values in quotes:

```
landsat download LC82190322014151LGN00 -p --pansharpen --clip "-30.6678274778,39.7258925095,-30.6278274778,39.7658925095" -d gis/landsat
```

**Comment by dkerkow** [comment]
@scisco I can confirm that it does not help. I've tested it. Using the `--clip=` syntax works though. Already preparing a PR to fix the docs accordingly.
