### ISSUE TITLE
Inconsistency detected by ld.so - Ubuntu 14.04 

### ISSUE THREAD

**Issue by rjhale1971** [developmentseed/landsat-util#15]
I think everything ran to completion - but it did toss an error at the end. I had a Final.tif in the Processed folder though. I only included the last part of the output (since that seemed most important). 

Convert: averaging
/usr/bin/gdal_calc.py:266: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  myNDVs=1*numpy.logical_or(myNDVs==1, myval==myNDV[i])
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
Input file size is 7789, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 7789, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 7789, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
/usr/bin/gdal_calc.py:266: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  myNDVs=1*numpy.logical_or(myNDVs==1, myval==myNDV[i])
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
/usr/bin/gdal_calc.py:266: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  myNDVs=1*numpy.logical_or(myNDVs==1, myval==myNDV[i])
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
/usr/bin/gdal_calc.py:266: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  myNDVs=1*numpy.logical_or(myNDVs==1, myval==myNDV[i])
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
convert.im6: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
World file written to '/tmp/tmpE2llmD/LC80210352014012LGN00/warp/LC80210352014012LGN00_B4.tfw'.

2014 Sep 21 17:13:49  :  Application.logger  (INFO) Elevation management: setting default height above ellipsoid to  0 meters
Writing /tmp/tmpE2llmD/LC80210352014012LGN00/final/pan.TIF...: 100% [**************************************************] (1e+02 seconds)
Inconsistency detected by ld.so: dl-close.c: 762: _dl_close: Assertion `map->l_init_called' failed!
subprocess.CalledProcessError: Command '['otbcli_BundleToPerfectSensor', '-inp', '/tmp/tmpE2llmD/LC80210352014012LGN00/warp/LC80210352014012LGN00_B8.TIF', '-inxs', '/tmp/tmpE2llmD/LC80210352014012LGN00/final/comp.TIF', '-out', '/tmp/tmpE2llmD/LC80210352014012LGN00/final/pan.TIF', 'uint16']' returned non-zero exit status 127
rjhale@gis2:~/landsat$ ls

**Comment by scisco** [comment]
`otbcli_BundleToPerfectSensor` is no longer used in the new version of landsat-util. Closing.
