### ISSUE TITLE
Could not find a version that satisfies the requirement usgs==0.1.9

### ISSUE THREAD

**Issue by jcabdala** [developmentseed/landsat-util#154]
I have this problem:
> (venv)$pip install landsat-util
> Collecting landsat-util
>   Using cached landsat-util-0.12.0.tar.gz
> Collecting usgs==0.1.9 (from landsat-util)
>   Could not find a version that satisfies the requirement usgs==0.1.9 (from landsat-util) (from versions: 0.1.0.dev0, 0.1.1.dev0, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7, 0.1.8)
> No matching distribution found for usgs==0.1.9 (from landsat-util)

I find usgs 1.9 in pypi but only have  0.18 https://pypi.python.org/pypi/usgs

**Comment by scisco** [comment]
@jcabdala you have to install it from our git repo. We have made a PR for the usgs package but it's not approved yet.

Try: `git+git://github.com/developmentseed/usgs@develop`

**Comment by scisco** [comment]
@jcabdala it seems that it doesn't work on a fresh install. Will fix now.

**Comment by jcabdala** [comment]
O, but I don't undestand why travis didn't crash.

**Comment by scisco** [comment]
@jcabdala released an updated version (0.12.1). Try `pip install landsat-util==0.12.1`
