### ISSUE TITLE
Problems in installing landsat-util on Ubuntu 14.04

### ISSUE THREAD

**Issue by fanta21** [developmentseed/landsat-util#159]
Hi.

I can't install the Landsat-util on my virtual machine, equipped with OS Ubuntu 14.04. The error that pops up is the following: 

Downloading/unpacking singledispatch (from tornado->matplotlib>=1.1.0->scikit-image>=0.11.3->landsat-util)
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Downloading/unpacking certifi (from tornado->matplotlib>=1.1.0->scikit-image>=0.11.3->landsat-util)
  Downloading certifi-2015.11.20.1-py2.py3-none-any.whl (368kB): 368kB downloaded
Downloading/unpacking backports-abc>=0.4 (from tornado->matplotlib>=1.1.0->scikit-image>=0.11.3->landsat-util)
  Downloading backports_abc-0.4-py2.py3-none-any.whl
Installing collected packages: landsat-util, geocoder, scikit-image, numpy, boto, rasterio, usgs2, polyline, six, scipy, homura, click, ratelim, networkx, affine, cligj, snuggs, click-plugins, enum34, requests-futures, humanize, tornado, nose, futures, backports.ssl-match-hostname, singledispatch, certifi, backports-abc
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/landsat_util-0.12.1.dist-info'

Is it a problem of permissions that I have to change or something more subtle?

**Comment by matthewhanson** [comment]
Hi @fanta21   This looks like tried to install as a regular user as it's trying to install into /usr/local/lib.

You'll want to either install as sudo, or install into a virtual environment.

**Comment by matthewhanson** [comment]
Haven't heard more, marking resolved.
