### ISSUE TITLE
pycurl Version: 7.43.0 and Name: landsat-util Version: 0.11.0

### ISSUE THREAD

**Issue by bmurch** [developmentseed/landsat-util#160]
Hello Developers,  

I am including the pycurl developer as it seems to me their issue that I found  during the landsat-util install.  

I recently updated my CentOS 7 distributions and had an older version of  landsat-util installed. (v.0.7?) After the upgrade, the program ceased to  function with this error:  

landsat search --cloud 100 --start "January 1 2014" --end "May 1  2015" --pathrow "227,056" --limit 10000  

Traceback (most recent call last):  
File "/usr/bin/landsat", line 5, in <module>  import landsat.landsat  File "/usr/lib/python2.7/site-packages/landsat/landsat.py", line 21, in  <module>  from image import Process, FileDoesNotExist  
File "/usr/lib/python2.7/site-packages/landsat/image.py", line 14, in  <module>  from rasterio.warp import reproject, RESAMPLING, transform  File "/usr/lib64/python2.7/site-packages/rasterio/warp.py", line 8, in  <module>  from rasterio._warp import _transform_geom, _reproject, RESAMPLING  File "__init__.pxd", line 864, in init rasterio._warp  (rasterio/_warp.cpp:22473)  
ValueError: numpy.ufunc has the wrong size, try recompiling  

So I took a look around and checked out a few things that I knew were needed  for the inital build but it ended with "Nothing to do" e.g.:  

yum install python-pip numpy scipy gdal gdal-devel gdal-libs gdal-python  atlas-devel atlas-static freetype freetype-devel Loaded plugins:  
fastestmirror, langpacks  
base |  3.6 kB 00:00:00  
epel/x86_64/metalink |  13 kB 00:00:00  
extras |  3.4 kB 00:00:00  
updates | 3.4 kB 00:00:00  
Loading mirror speeds from cached hostfile  
* base: centos.mirror.constant.com  
* epel: reflector.westga.edu  
* extras: mirror.ash.fastserv.com  
* updates: pubmirrors.dal.corespace.com Package python-pip-7.1.0-1.el7.noarch  
already installed and latest version Package 1:numpy-1.7.1-11.el7.x86_64  
already installed and latest version Package scipy-0.12.1-3.el7.x86_64  
already installed and latest version Package gdal-1.11.2-2.el7.x86_64 already  
installed and latest version Package gdal-devel-1.11.2-2.el7.x86_64 already  
installed and latest version Package gdal-libs-1.11.2-2.el7.x86_64 already  
installed and latest version Package gdal-python-1.11.2-2.el7.x86_64 already  
installed and latest version Package atlas-devel-3.10.1-10.el7.x86_64 already  
installed and latest version Package atlas-static-3.10.1-10.el7.x86_64  
already installed and latest version Package freetype-2.4.11-11.el7.x86_64  
already installed and latest version Package  
freetype-devel-2.4.11-11.el7.x86_64 already installed and latest version  
Nothing to do  

Then I noticed that there was an updated version of landsat-util so I:  
pip install -U landsat-util  but that failed.  

I then:  
yum install libcurl-devel  
pip install --upgrade pip  
pip install --upgrade setuptools  
pip install -U landsat-util  

However, /usf/bin/landsat failed:  
landsat search --cloud 100 --start "January 1  
2014" --end "May 1 2015" --pathrow "227,056" --limit 10000  
Traceback (most recent call last):  
File "/usr/bin/landsat", line 5, in <module>  
import landsat.landsat  
File "/usr/lib/python2.7/site-packages/landsat/landsat.py", line 15, in  
<module>  
import pycurl  
ImportError: pycurl: libcurl link-time ssl backend (nss) is different from  
compile-time ssl backend (none/other)  

And then I noticed that my yum was destroyed:  
yum info perl  
There was a problem importing one of the Python modules  required to run yum. The error leading to this problem was:  

pycurl: libcurl link-time ssl backend (nss) is different from compile-time  
ssl backend (none/other)  

Please install a package which provides this module, or  verify that the module is installed correctly.  

It's possible that the above module doesn't match the  current version of Python, which is:  
2.7.5 (default, Nov 20 2015, 02:00:19)  
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]  

If you cannot solve this problem yourself, please go to  the yum faq at:  http://yum.baseurl.org/wiki/Faq  

So I looked around and found:  
http://stackoverflow.com/questions/21096436/ssl-backend-error-when-using-openssl  and I realized that openssl had had an issue identified by CERT and I had very  recently updated openssl.x86_64  

The link above suggested setting an env:  
export PYCURL_SSL_LIBRARY=nss  
And then uninstalled pycurl and reinstalled it:  
[site-packages]# pip uninstall pycurl  
Uninstalling pycurl-7.43.0:  
/usr/lib64/python2.7/site-packages/curl/__init__.py  
/usr/lib64/python2.7/site-packages/curl/__init__.pyc  
/usr/lib64/python2.7/site-packages/pycurl-7.43.0-py2.7.egg-info  
/usr/lib64/python2.7/site-packages/pycurl.so  
/usr/share/doc/pycurl/AUTHORS  
/usr/share/doc/pycurl/COPYING-LGPL  
/usr/share/doc/pycurl/COPYING-MIT  
/usr/share/doc/pycurl/ChangeLog  
/usr/share/doc/pycurl/INSTALL.rst  
/usr/share/doc/pycurl/README.rst  
/usr/share/doc/pycurl/RELEASE-NOTES.rst  
/usr/share/doc/pycurl/examples/basicfirst.py  
/usr/share/doc/pycurl/examples/file_upload.py  
/usr/share/doc/pycurl/examples/linksys.py  
/usr/share/doc/pycurl/examples/quickstart/file_upload_buffer.py  
/usr/share/doc/pycurl/examples/quickstart/file_upload_real.py  
/usr/share/doc/pycurl/examples/quickstart/file_upload_real_fancy.py  
/usr/share/doc/pycurl/examples/quickstart/follow_redirect.py  
/usr/share/doc/pycurl/examples/quickstart/form_post.py  
/usr/share/doc/pycurl/examples/quickstart/get.py  
/usr/share/doc/pycurl/examples/quickstart/get_python2.py  
/usr/share/doc/pycurl/examples/quickstart/get_python3.py  
/usr/share/doc/pycurl/examples/quickstart/response_headers.py  
/usr/share/doc/pycurl/examples/quickstart/response_info.py  
/usr/share/doc/pycurl/examples/quickstart/write_file.py  
/usr/share/doc/pycurl/examples/retriever-multi.py  
/usr/share/doc/pycurl/examples/retriever.py  
/usr/share/doc/pycurl/examples/sfquery.py  
/usr/share/doc/pycurl/examples/smtp.py  
/usr/share/doc/pycurl/examples/ssh_keyfunction.py  
/usr/share/doc/pycurl/examples/xmlrpc_curl.py  
Proceed (y/n)? y  
Successfully uninstalled pycurl-7.43.0  

[site-packages]# pip install --compile pycurl  
Collecting pycurl  
Using cached pycurl-7.43.0.tar.gz  
Installing collected packages: pycurl  
Running setup.py install for pycurl ... done  
Successfully installed pycurl-7.43.0  

After that both landsat and yum worked again.  

pycurl developers:  
I am curious, was the issue due to the recent change to openssl? And you have  
not recompiled landsat-util against the lastest openssl?  

landsat-util developers:  
We noticed that some of the queries (both old and new versions of  
landsat-util) failed to locate the latest data that is available on  
http://earthexplorer.usgs.gov/ Is there a reason that these data are not  
found with the landsat-util?

**Comment by scisco** [comment]
@bmurch our deployment of landsat-api which powers the search command had an issue for a few weeks and was not updated. We have fixed it and you should be able to see the latest data.

**Comment by bmurch** [comment]
I don't believe that the latest data is searchable, nor all of it accessible:

eg:
landsat search -p "001,050" --latest 1
{
    "limit": 25,
    "results": [
        {
            "cloud": 6.85,
            "date": "2016-02-23",
            "path": "001",
            "row": "050",
            "sat_type": "L8",
            "sceneID": "LC80010502016054LGN00",
            "thumbnail": "http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016054LGN00.jpg"
        }
    ],
    "status": "SUCCESS",
    "total": 21,
    "total_returned": 1
}
['Search completed!']

Yet these are all available to view on earthexplorer:

http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016054LGN00.jpg
http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016070LGN00.jpg
http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016086LGN00.jpg

AND, the LC80010502016054LGN00 and LC80010502016070LGN00 scenes are able to be downloaded with the "landsat download" command even though not found via search.

landsat download LC80010502016054LGN00
===> Downloading: LC80010502016054LGN00.tar.bz
   100%    573.6 MiB      38.2 MiB/s            0:00:00 ETA
     stored at /optics1/home1/oo_processing/landsat/downloads
===> Download Completed
===> Done!
Time spent : 18.71 seconds
searobin 134 :/optics1/home1/oo_processing> landsat download LC80010502016070LGN00
===> Downloading: LC80010502016070LGN00.tar.bz
   100%    570.5 MiB      42.5 MiB/s            0:00:00 ETA
     stored at /optics1/home1/oo_processing/landsat/downloads
===> Download Completed
===> Done!
Time spent : 15.69 seconds
searobin 135 :/optics1/home1/oo_processing> landsat download LC80010502016086LGN00
Time spent : 0.14 seconds
Traceback (most recent call last):
  File "/usr/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/lib/python2.7/site-packages/landsat/landsat.py", line 475, in __main__
    exit(*main(args))
  File "/usr/lib/python2.7/site-packages/landsat/landsat.py", line 385, in main
    downloaded = d.download(args.scenes, bands)
  File "/usr/lib/python2.7/site-packages/landsat/downloader.py", line 80, in download
    self.google_storage(scene, self.download_dir)
  File "/usr/lib/python2.7/site-packages/landsat/downloader.py", line 113, in google_storage
    raise RemoteFileDoesntExist('%s is not available on Google Storage' % filename)
landsat.downloader.RemoteFileDoesntExist: LC80010502016086LGN00.tar.bz is not available on Google Storage
