### ISSUE TITLE
Pip install: usgs2 not available 

### ISSUE THREAD

**Issue by lockwooddev** [developmentseed/landsat-util#167]
When I install landsat-util (0.12.1), it fails on:

`Downloading/unpacking usgs2==0.2.0 (from landsat-util)
  Could not find any downloads that satisfy the requirement usgs2==0.2.0 (from landsat-util)`

When you visit the presumed location of the package on pypi, you get a 404 page:
[https://pypi.python.org/pypi/usgs2](https://pypi.python.org/pypi/usgs2)

Could it be this requirement was removed?

**Comment by scisco** [comment]
Oh, this is all my fault. Will release a hotfix shortly. Thanks for reporting this.

**Comment by sgillies** [comment]
@scisco curious: where's the usgs2 package developed? Will https://pypi.python.org/pypi/usgs work in the meanwhile?

**Comment by scisco** [comment]
@sgillies it was just a fork and was merged back to usgs. I needed it for a project and couldn't wait for the fork to be merged so I created usgs2. I reverted back to usgs afterwards.

**Comment by scisco** [comment]
@lockwooddev the updated version with fixed dependency is on pypi now. `pip install landsat-util==0.12.2`

**Comment by lockwooddev** [comment]
Installation works now. Thank you for the help :)
