### ISSUE TITLE
The latest data not all searchable, nor accessible

### ISSUE THREAD

**Issue by bmurch** [developmentseed/landsat-util#176]
I have opened a new issue as I don't believe the issue of timely data access has been resolved.

I don't believe that the latest data is searchable, nor all of it accessible:

eg:
landsat search -p "001,050" --latest 1
{
"limit": 25,
"results": [
{
"cloud": 6.85,
"date": "2016-02-23",
"path": "001",
"row": "050",
"sat_type": "L8",
"sceneID": "LC80010502016054LGN00",
"thumbnail": "http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016054LGN00.jpg"
}
],
"status": "SUCCESS",
"total": 21,
"total_returned": 1
}
['Search completed!']

OR:

landsat search -p "001,050" -s 01/01/2016 -e 04/04/2016
===> 4 items were found
{
    "limit": 10,
    "results": [
        {
            "cloud": 9.08,
            "date": "2016-02-07",
            "path": "001",
            "row": "050",
            "sat_type": "L8",
            "sceneID": "LC80010502016038LGN00",
            "thumbnail": "http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016038LGN00.jpg"
        },
        {
            "cloud": 22.33,
            "date": "2016-01-06",
            "path": "001",
            "row": "050",
            "sat_type": "L8",
            "sceneID": "LC80010502016006LGN00",
            "thumbnail": "http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016006LGN00.jpg"
        },
        {
            "cloud": 6.85,
            "date": "2016-02-23",
            "path": "001",
            "row": "050",
            "sat_type": "L8",
            "sceneID": "LC80010502016054LGN00",
            "thumbnail": "http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016054LGN00.jpg"
        },
        {
            "cloud": 7.44,
            "date": "2016-01-22",
            "path": "001",
            "row": "050",
            "sat_type": "L8",
            "sceneID": "LC80010502016022LGN00",
            "thumbnail": "http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016022LGN00.jpg"
        }
    ],
    "status": "SUCCESS",
    "total": 4,
    "total_returned": 4
}
['Search completed!']

Yet these are available to view on EarthExplorer:

http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016070LGN00.jpg
http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016086LGN00.jpg

AND, the LC80010502016070LGN00 scene was able to be downloaded with the "landsat download" command even though  LC80010502016070LGN00 was not found via search.

landsat download LC80010502016070LGN00
===> Downloading: LC80010502016070LGN00.tar.bz
100% 570.5 MiB 42.5 MiB/s 0:00:00 ETA
stored at /optics1/home1/oo_processing/landsat/downloads
===> Download Completed
===> Done!
Time spent : 15.69 seconds

When I added the comment to the closed issue #160, Scene 086 was not found in search nor was it available for download.

searobin 135 :/optics1/home1/oo_processing> landsat download LC80010502016086LGN00
Time spent : 0.14 seconds
Traceback (most recent call last):
File "/usr/bin/landsat", line 8, in
landsat.landsat.main()
File "/usr/lib/python2.7/site-packages/landsat/landsat.py", line 475, in main
exit(*main(args))
File "/usr/lib/python2.7/site-packages/landsat/landsat.py", line 385, in main
downloaded = d.download(args.scenes, bands)
File "/usr/lib/python2.7/site-packages/landsat/downloader.py", line 80, in download
self.google_storage(scene, self.download_dir)
File "/usr/lib/python2.7/site-packages/landsat/downloader.py", line 113, in google_storage
raise RemoteFileDoesntExist('%s is not available on Google Storage' % filename)
landsat.downloader.RemoteFileDoesntExist: LC80010502016086LGN00.tar.bz is not available on Google Storage

However, today (doy 095) it is available for download, but still not found with the search.:
searobin 166 :/optics1/virtual_ant/S4P_VIIRS_H5> landsat download LC80010502016086LGN00
===> Downloading: LC80010502016086LGN00.tar.bz
   100%    706.1 MiB      13.4 MiB/s            0:00:00 ETA
     stored at /optics1/home1/oo_processing/landsat/downloads
===> Download Completed
===> Done!
Time spent : 52.61 seconds

It appears there is some lag between the time the files are available on EarthExplorer (it would be good to know how long that is.) And there is still a problem with your search as it doesn't return files that landsat can indeed download.

Thanks,
Brock

**Comment by scisco** [comment]
@bmurch thanks for reporting. I'll take it a look and report back

**Comment by mmeisinger** [comment]
I can confirm. This is quite disconcerting for the use within our application. Today (4/20/16) when I look for path 31,36 after 2/1/16, I get the following (shortened) results with 0.13.0:

landsat search -p 31,36 -s 2016-02-01 -e 2016-04-30 -c 100

http://earthexplorer.usgs.gov/browse/landsat_8/2016/031/036/LC80310362016040LGN00.jpg
http://earthexplorer.usgs.gov/browse/landsat_8/2016/031/036/LC80310362016056LGN00.jpg

However, 3 further scenes available in EarthExplorer and on AWS S3 are not reported:

http://earthexplorer.usgs.gov/browse/landsat_8/2016/031/036/C80310362016072LGN00.jpg
http://earthexplorer.usgs.gov/browse/landsat_8/2016/031/036/LC80310362016088LGN00.jpg
http://earthexplorer.usgs.gov/browse/landsat_8/2016/031/036/LC80310362016104LGN00.jpg

So the lag is around 6 weeks in this case.

(I've tried it with a query for ~20 different scenes and they are all with similar lag)

Is there any chance of reducing this lag or working around, in particular if it's caused by an outdated index rather than actual data availability?

**Comment by scisco** [comment]
@mmeisinger @bmurch Sorry for the outdated results. We only run an experimental API that is not ready for production use. You can always run your instance of the API and point the landsat-util to use your version for searching.

Nevertheless, I just updated our version of landsat-api and put in a place a procedure that will ensure the API will update regularly like before.

```
$ landsat search -p "001,050" --latest 1                    
{
    "limit": 25,
    "results": [
        {
            "cloud": 15.71,
            "date": "2016-04-27",
            "path": "001",
            "row": "050",
            "sat_type": "L8",
            "sceneID": "LC80010502016118LGN00",
            "thumbnail": "http://earthexplorer.usgs.gov/browse/landsat_8/2016/001/050/LC80010502016118LGN00.jpg"
        }
    ],
    "status": "SUCCESS",
    "total": 23,
    "total_returned": 1
}
['Search completed!']
```
