### ISSUE TITLE
Calculated clould and snow pixel percentage may be larger than the reality

### ISSUE THREAD

**Issue by haoliangyu** [developmentseed/landsat-util#181]
The current method is to add up the pixel number of all snow and cloud types. But a pixel could be identified as snow and cloud with high confidence. For example, a pixel with QA code `56320` is considered as snow ([code](https://github.com/developmentseed/landsat-util/blob/f0c229b9b7d466ff90c39ea69cf136db8d6130e8/landsat/image.py#L294)), but also has high confidence to be cloud. Then, a pixel with QA code `61440` is in the cloud catalog ([code](https://github.com/developmentseed/landsat-util/blob/f0c229b9b7d466ff90c39ea69cf136db8d6130e8/landsat/image.py#L295)), but also has high confidence to be snow. It results in an inflated cloud and snow percentage.

**Comment by scisco** [comment]
It is fixed in #183
