### ISSUE TITLE
What exactly is the process command doing?

### ISSUE THREAD

**Issue by CMCDragonkai** [developmentseed/landsat-util#186]
The docs says:

> You can process your downloaded tiles with our custom image processing algorithms. In addition, you can choose to pansharpen your images and specify which bands to process.

What is `landsat process ...`?

**Comment by scisco** [comment]
@CMCDragonkai You can create a true color or false color image from three landsat bands using `landsat process`. For example, if you download bands 4, 3, 2 of a scene using this command: `landsat download LC80410322016062LGN00 -b 432`, then you can process it to a true color image using:

    $ landsat process ~/landsat/downloads/LC80410322016062LGN00 -b 432

**Comment by CMCDragonkai** [comment]
Thanks, so there's a false colour version of the command?

**Comment by JorgeGT** [comment]
You can combine arbitrary bands to create different false color images that highlight different features of the scene. For a look at different interesting possibilities see [this page](http://www.harrisgeospatial.com/Home/NewsUpdates/TabId/170/ArtMID/735/ArticleID/14305/The-Many-Band-Combinations-of-Landsat-8.aspx). 

You will notice they list first the combination that gives natural color (4,3,2) and then different false color possibilities. For instance (5,4,3) gives "Traditional Color Infrared". For this you would use:

    landsat process ~/landsat/downloads/LC80410322016062LGN00 -b 543

**Comment by CMCDragonkai** [comment]
@JorgeGT thanks that makes sense. I also read your recent blog post, very useful.
