### ISSUE TITLE
search command accepted date formats

### ISSUE THREAD

**Issue by negroscuro** [developmentseed/landsat-util#190]
Hello,
I read the documentation saying this command accept most date formats but I am having erratic behaviors depending on the date format.
Which are the accepted date formats?

I used YYYY-mm-dd or YYYY/mm/dd
also dd-mm-YYYY or dd/mm/YYYY --> I think this is not working properly.
Recently I tried with mm-dd-YYYY or mm/dd/YYYY

Thank you for your suuport and help.
Cheers,
Mario.

**Comment by JorgeGT** [comment]
If Im not mistaken the preferred format is YYYY-MM-DD. From [`search.py`](https://github.com/developmentseed/landsat-util/blob/develop/landsat/search.py#L41):

```
:param start_date:
    Date string. format: YYYY-MM-DD
```

**Comment by negroscuro** [comment]
I will use that one then, thank you.
