### ISSUE TITLE
Quickly view thumbnails directly in your terminal

### ISSUE THREAD

**Issue by daleroberts** [developmentseed/landsat-util#195]
Hi guys. You might like my new tool, I use it in combination with `landsat-util` in my examples:

https://github.com/daleroberts/tv

**Comment by drewbo** [comment]
Awesome tool and thanks for the mention in your repo!

**Comment by scisco** [comment]
pretty cool. thanks

**Comment by drewbo** [comment]
Noting the new [`bv` repo](https://github.com/daleroberts/bv) as well
