### ISSUE TITLE
ValueError when trying to run landsat.py 0.13.0

### ISSUE THREAD

**Issue by saultdon** [developmentseed/landsat-util#202]
I installed landsat-util 0.13.0 locally with:
`pip2 install --user landsat-util`

and then created an alias as:
`landsat='python2 /home/saultdon/.local/lib/python2.7/site-packages/landsat/landsat.py'`

But when I try to run either:
`landsat --help`
`python2 /home/saultdon/.local/lib/python2.7/site-packages/landsat/landsat.py --help`

The following error appears:
`Traceback (most recent call last):
  File "/home/saultdon/.local/lib/python2.7/site-packages/landsat/landsat.py", line 24, in <module>
    from .downloader import Downloader, IncorrectSceneId, RemoteFileDoesntExist, USGSInventoryAccessMissing
ValueError: Attempted relative import in non-package`

**Comment by drewbo** [comment]
@saultdon you will need to run the package from the binary rather than the script. I think something like:
```
landsat='python2 /home/saultdon/.local/lib/python2.7/site-packages/landsat/bin/landsat'
```

should work. Let me know if you have any other issues

**Comment by okanisis** [comment]
Thanks for the tips drewbo, but I don't have a bin directory there for some reason...

```
saultdon@archasus ~ % ls .local/lib/python2.7/site-packages/landsat/
decorators.py   downloader.py   image.py   __init__.py   landsat.py   maps       mixins.pyc  ndvi.pyc   search.pyc   settings.pyc  uploader.pyc  utils.pyc
decorators.pyc  downloader.pyc  image.pyc  __init__.pyc  landsat.pyc  mixins.py  ndvi.py     search.py  settings.py  uploader.py   utils.py
```

**Comment by okanisis** [comment]
ah, found it, it's in ~/.local/bin

So a simple update of the PATH to include that, or making the alias as:

```
alias landsat='~/.local/bin/landsat'
```
