### ISSUE TITLE
Installing on Windows 7

### ISSUE THREAD

**Issue by Mavromatika** [developmentseed/landsat-util#203]
Hi,
I've been trying to install landsat-util on my machine running Win 7. 
I tried what is suggested in the documentation under "Other systems", but it didn't work. The first command (python setup.py numpy six) doesn't work. 
Do you have any suggestions ? I do have machines running Linux at home but none of them have enough RAM.
Thank you in advance.

**Comment by Mavromatika** [comment]
Hi,
I'm still stuck. I'd really appreciate some help !
Regards.

**Comment by scisco** [comment]
I haven't really been able to install this tool on Windows. There is docker image though that you can use on windows. If you are familiar with docker, this is how you can use it there:

https://pythonhosted.org/landsat-util/installation.html#docker

**Comment by JorgeGT** [comment]
Alternatively if you can update to Windows 10 you may be able to install this tool in [Bash on Ubuntu on Windows](https://www.linux.com/news/bash-windows-what-does-it-mean) which is an Ubuntu user space on Windows with access to the filesystem, etc. You can the follow the instruction for Ubuntu.

**Comment by Mavromatika** [comment]
Thank you, using Docker (which I didn't know before) worked.
