### ISSUE TITLE
Issue with GeoJSON to gejosnio

### ISSUE THREAD

**Issue by noelmas** [developmentseed/landsat-util#211]
When I run this command:

landsat search --lat 38.9004204 --lon -77.0237117 --geojson | geojsonio

I get:

Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule
Polygons and MultiPolygons should follow the right-hand rule

Is this something to do with update to GeoJSON spec since tool was built?

**Comment by drewbo** [comment]
Added to `geojsonio-cli` in [`0.2.3`](https://github.com/mapbox/geojsonio-cli/releases/tag/v0.2.3)
