### ISSUE TITLE
landsat-util on docker, search commande don't work !

### ISSUE THREAD

**Issue by Mounirsky** [developmentseed/landsat-util#212]
Dear sir,

I'm using landsat-util on docker, and when I try the search command as follow :

`landsat search -p "26,202" --latest 5 --json`

it fail ! here is the error returned :
```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[u'No matches found!', 1]
```
Can you please help me to fix this issue ?

Regards,

**Comment by drewbo** [comment]
@Mounirsky I believe the api is correctly returning "No matches" for that path/row combination as it is a nighttime scene. The metadata for most nighttime scenes aren't provided by USGS via the Landsat-8 csv file that we use to populate the API. Let me know if that helps.

**Comment by Mounirsky** [comment]
Right ! I made 2 mistakes : 
1 - path,row should have 3 numbers like "202,026"
2 - Date format is (mm/dd/yyyy)
I think it is will be good if you precise it on the API help :+1: 
Regards,
