### ISSUE TITLE
landsat download only the BQA.TIF file !!

### ISSUE THREAD

**Issue by Mounirsky** [developmentseed/landsat-util#213]
Dir sir,

I'm using the following download command : 
> landsat download LC82020262013189LGN00 -d /mnt/vol1/ 
but it down load only the metadata and the BQA.TIF files !
I'v checked that the image is available at this [link](https://s3-us-west-2.amazonaws.com/landsat-pds/L8/202/026/LC82020262013189LGN00/index.html)
I want to get the whole zip file of every new LC8 image using landsat-util, how to do ?

Regards.

**Comment by drewbo** [comment]
This is caused by the existing bug #191, looking at the relevant PR soon

**Comment by drewbo** [comment]
Closed in #217
