### ISSUE TITLE
Nonfunctioning end-date

### ISSUE THREAD

**Issue by frankwang95** [developmentseed/landsat-util#216]
It looks to me like the API at api.developmentseed.org is not handling end-dates properly when the end-date given is sooner than today. The following link returns no results

> https://api.developmentseed.org/landsat?search=acquisitionDate:[2009-01-01+TO+2015-01-01]

... but this one works just fine:

>https://api.developmentseed.org/landsat?search=acquisitionDate:[2009-01-01+TO+2018-01-01]

Anyone know what's going on?

**Comment by egofer** [comment]
The API must have stopped working correctly. For example, this no longer works:

landsat search --lat 38.9004204 --lon -77.0237117 --latest 2 --cloud 80
landsat search --latest 5  -p 166,60
landsat search --start "january 1 2015" --end "april 10 2015" -p 166,60

[u'No matches found!', 1]

... and this returns a single result for this year:

landsat search --lat 38.9004204 --lon -77.0237117 --latest 2 --cloud 90

Problems with dates and change of year?

**Comment by drewbo** [comment]
Hi all, we had an issue with some records getting dumped from the instance powering the API; we're working now on repopulating the files and adding better backups so this doesn't happen again!

**Comment by frankwang95** [comment]
Thanks drewbo, will you send us a notification when the API is back online?

**Comment by bucricket** [comment]
Yes please let us know when its back up!  Thanks for your hard work on this awesome tool!

**Comment by drewbo** [comment]
API records at `238591` and counting (albeit slowly). I'm not sure when we'll exactly see the "finished" signal when everything is back but it is happening in an ongoing background task as we speak

**Comment by drewbo** [comment]
All back up!
