### ISSUE TITLE
Problem with landsat search

### ISSUE THREAD

**Issue by rs2247** [developmentseed/landsat-util#218]
When I try to run the example landsat search --lat 38.9004204 --lon -77.0237117
I get the following error: 

Traceback (most recent call last):
  File "/usr/local/bin/landsat", line 8, in <module>
    landsat.landsat.__main__()
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 488, in __main__
    print(main(args))
  File "/usr/local/lib/python2.7/dist-packages/landsat/landsat.py", line 357, in main
    geojson=args.geojson)
  File "/usr/local/lib/python2.7/dist-packages/landsat/search.py", line 141, in search
    result['total'] = r_dict['meta']['results']['total']
KeyError: 'results'

Any ideas what it might be? I've already checked and all the packages in requirements.txt are installed (and at its correct version).

When I try to use the download command everything works.

Thanks!

**Comment by drewbo** [comment]
Thanks for the report @rs2247, I think landsat-api is redirecting now to an updated API which doesn't have `['meta']['results']['total']` bur rather `['meta']['found']` so we'll need to update the reference.

**Comment by drewbo** [comment]
Closed in #217

**Comment by jlengrand** [comment]
I still see the same error .

Checking My environment, this is the version I run on (landsat_util              0.13.1                   py35_0    conda-forge)

Is that expected?

**Comment by jlengrand** [comment]
Interesting, applying the changes to search.py mentioned [here](https://github.com/developmentseed/landsat-util/pull/217/files#diff-aad60e01320530a890e2f7a9172a1e39L141) fix the issue. 

Looking further, it seems that conda-forge packages version 0.13.0 as 0.13.1.

Checking the site-packages:

`.//__init__.py:__version__ = '0.13.0'`

But in my conda env : 

`landsat_util 0.13.1 py35_0 conda-forge`

**Comment by jlengrand** [comment]
I think I understand why. If I check the latest archive (https://github.com/developmentseed/landsat-util/archive/v0.13.1.tar.gz), the content is still 0.13.0

Would we need to make a new release for it to work fine?
