### ISSUE TITLE
File Naming

### ISSUE THREAD

**Issue by jai2125** [developmentseed/landsat-util#224]
I am processing many landsat images at a time using the util. Asking if it is possible to rename files during the processing, clipping, and pansharpening.

The command I am using looks as follows:
landsat process /Users/jonathanizen/landsat/downloads/LC80040562014021LGN00 --pansharpen --clip=-67.43075776,6.243551795,-67.54370066,6.130518795

The file name defaults to a name such as this when completed:
LC80040562014021LGN00_bands_432_pan_clipped_faqzKembe@z`UlaU.TIF

I am hoping to rename the file with the name of the city or town that is in the original table I used to create the bounds of the image. Is there an additional command I can use to rename the files with a custom name?

**Comment by drewbo** [comment]
Hi @jai2125, I don't think we currently have a command to rename while processing. Happy to review PRs on this or suggestions; it's not currently on our roadmap

**Comment by matthewhanson** [comment]
@jai2125 
While we making some minor updates to landsat-util it will be deprecated in favor of using our new [sat-api](https://medium.com/devseed/sat-api-an-api-for-spatiotemporal-asset-catalogs-88c3c78fdb0e) and [sat-search](https://github.com/sat-utils/sat-search/). sat-search does allow renaming of files when download but it does not do processing like landsat-util does. The processing functionality of landsat-util will be replaced with a new version of [sat-process](https://github.com/sat-utils/sat-process).
