### ISSUE TITLE
landsat process reprojects from native CRS to EPSG:3857

### ISSUE THREAD

**Issue by negroscuro** [developmentseed/landsat-util#228]
Hello,
I do not know why landsat process changed projection while generating an RGB tif file. 
I need it in the original CRS.
Can this be customized or avoided somehow?
thank you in advance.
Maroi.

**Comment by matthewhanson** [comment]
Hi @negroscuro , there is currently no option to specify that, or turn off reprojection, although it's something that should definitely be added. For now, as a workaround, you should be able to edit the two lines here 
https://github.com/developmentseed/landsat-util/blob/develop/landsat/image.py#L71

Just drop in the EPSG code for the correct UTM projection of your scene.

**Comment by negroscuro** [comment]
Thank you very much for the landsat-tool itself, it is useful, and also thank you for answering about this.

I noticed this because i am loading landsat data with time dimension into a tool that is giving me problems because of resolution changes, when a raster is reprojected the resolution slightly changed and then it is not possible to import it by using the tool since time dimension is restricting data upload requirements.

cheers,
Mario.
