### ISSUE TITLE
returned non-zero exit status 4

### ISSUE THREAD

**Issue by vascobnunes** [developmentseed/landsat-util#23]
Hi. Congratulations on this very usefull tool.
I'm having trouble processing the images after dowloading them.
Here's the console text:

"C:\Programs\landsat-util-master>python C:\Programs\landsat-util-master\landsat\l
andsat.py search --download --imageprocess --cloud 20 --start "january 1 2014" -
-end "april 10 2014" pr 204 032
1 items were found
{
    "limit": 100,
    "results": [
        {
            "cloud": 4.16,
            "date": "2014-03-19",
            "path": "204",
            "row": "032",
            "sat_type": "L8",
            "sceneID": "LC82040322014078LGN00",
            "thumbnail": "http://earthexplorer.usgs.gov/browse/landsat_8/2014/20
4/032/LC82040322014078LGN00.jpg"
        }
    ],
    "status": "SUCCESS",
    "total": 1,
    "total_returned": 1
}
Starting the download:
Skipping existing item: file://C:\Users\Administrator/landsat/zip/LC820403220140
78LGN00.tar.bz
1 images were downloaded
c:\users\admini~1\appdata\local\temp\1\tmpybepa2/LC82040322014078LGN00 folder cr
eated
c:\users\admini~1\appdata\local\temp\1\tmpybepa2/LC82040322014078LGN00/warp fold
er created
c:\users\admini~1\appdata\local\temp\1\tmpybepa2/LC82040322014078LGN00/scaled fo
lder created
c:\users\admini~1\appdata\local\temp\1\tmpybepa2/LC82040322014078LGN00/final fol
der created
Unzipping LC82040322014078LGN00 - It might take some time
Creating output file that is 7828P x 7932L.
Processing input file c:\users\admini~1\appdata\local\temp\1\tmpybepa2/LC8204032
2014078LGN00/LC82040322014078LGN00_B4.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7828P x 7932L.
Processing input file c:\users\admini~1\appdata\local\temp\1\tmpybepa2/LC8204032
2014078LGN00/LC82040322014078LGN00_B3.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7828P x 7932L.
Processing input file c:\users\admini~1\appdata\local\temp\1\tmpybepa2/LC8204032
2014078LGN00/LC82040322014078LGN00_B2.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 15655P x 15862L.
Processing input file c:\users\admini~1\appdata\local\temp\1\tmpybepa2/LC8204032
2014078LGN00/LC82040322014078LGN00_B8.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Starting the Min/Max process with designated -percent cut- for band 4 of LC82040
322014078LGN00
...
Finished processing band 4 of LC82040322014078LGN00
Starting the Min/Max process with designated -percent cut- for band 3 of LC82040
322014078LGN00
...
Finished processing band 3 of LC82040322014078LGN00
Starting the Min/Max process with designated -percent cut- for band 2 of LC82040
322014078LGN00
...
Finished processing band 2 of LC82040322014078LGN00
scaling pan to min max with 2% cut for band 4
Input file size is 7828, 7932
0...10...20...30...40...50...60...70...80...90...100 - done.
scaling pan to min max with 2% cut for band 3
Input file size is 7828, 7932
0...10...20...30...40...50...60...70...80...90...100 - done.
scaling pan to min max with 2% cut for band 2
Input file size is 7828, 7932
0...10...20...30...40...50...60...70...80...90...100 - done.
Invalid Parameter - -combine
Traceback (most recent call last):
  File "C:\Programs\landsat-util-master\landsat\landsat.py", line 285, in <modul
e>
    __main__()
  File "C:\Programs\landsat-util-master\landsat\landsat.py", line 282, in __main
__
    main(args)
  File "C:\Programs\landsat-util-master\landsat\landsat.py", line 236, in main
    p.full()
  File "C:\Programs\landsat-util-master\landsat\image_helper.py", line 108, in f
ull
    self._combine()
  File "C:\Programs\landsat-util-master\landsat\image_helper.py", line 340, in _
combine
    subprocess.check_call(argv)
  File "C:\OSGeo4W64\apps\Python27\lib\subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['convert', '-identify', '-combine', u'c
:\\users\\admini~1\\appdata\\local\\temp\\1\\tmpybepa2/LC82040322014078LGN00/war
p/LC82040322014078LGN00_B4.TIF', u'c:\\users\\admini~1\\appdata\\local\\temp\\1\
\tmpybepa2/LC82040322014078LGN00/warp/LC82040322014078LGN00_B3.TIF', u'c:\\users
\\admini~1\\appdata\\local\\temp\\1\\tmpybepa2/LC82040322014078LGN00/warp/LC8204
0322014078LGN00_B2.TIF', u'c:\\users\\admini~1\\appdata\\local\\temp\\1\\tmpybep
a2/LC82040322014078LGN00/final/rgb-null.TIF']' returned non-zero exit status 4
"

**Comment by scisco** [comment]
@vascobnunes we removed the imagemagick dependency. Please upgrade and try again. Let us if the problem persists.
