### ISSUE TITLE
Failed installation - OS X

### ISSUE THREAD

**Issue by ivanhigueram** [developmentseed/landsat-util#231]
Hello, 

I have been trying to install `landsat-util` in my local OS X machine. First, I tried install the package using a `virtualenv` with Python 2.7 and basic packages. Nonetheless the installation was not successful. Second, I ignore the possible conflicts with other libraries of Python and install the package using: `pip install landsat-util==0.13.0`. 

Before downloading some libraries, the following error message appear: 

`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j_/1vftj1cj4s18rg9z712_3h4c0000gn/T/pip-build-gjblk250/matplotlib/
`

I have uninstall `matplotlib` (and tried a virtual environment), but I am kind of lost here. There is something that I am doing wrong? 

Thanks!

**Comment by drewbo** [comment]
Hi @ivanhigueram did you end up getting this resolved?

**Comment by ivanhigueram** [comment]
Yes drewbo! Finally I get to install the utility in both the AWS instance and my local Mac machine by installing a older version of `matplotlib: 1.5.1` Nonetheless, I am still getting error running `$: landsat search`. I opened a issue a few hours ago with those error messages.  Thanks for your prompt answer.
