### ISSUE TITLE
Search function not working 100%

### ISSUE THREAD

**Issue by bchate** [developmentseed/landsat-util#24]
Hi and thanks for the nice tool you are developing.

I started to play with it and noticed the search function is not providing 100% of the scene available (compared to the same search in Glovis).
As an example I searched for a LS8 image path/row 190/036 between 1 october 2014 and 11 december 2012 (even with 20% cloud cover) and landsat-util returned none, when glovis found 3 (max 6% cloud cover).
On the other side, once the sceneid found in Glovis, landsat-util is able to download it.

Best regards,
Bruno

**Comment by scisco** [comment]
We finally fixed this issue. There was a problem with the cron job the was supposed to update the metadata everyday. Thanks for reporting.
