### ISSUE TITLE
GDAL issue

### ISSUE THREAD

**Issue by MYM2107** [developmentseed/landsat-util#34]
Hi,
I installed all dependencies but I'm running into this error (regarding GDAL)

//
i-a$ landsat -h
ImportError: dlopen(//anaconda/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Symbol not found: __ZNSt8ios_base4InitD1Ev
  Referenced from: //anaconda/lib/python2.7/site-packages/osgeo/_gdal.so
  Expected in: dynamic lookup
//

I installed GDAL through Macport but I also have anaconda installed on my system. 

Thanks

**Comment by scisco** [comment]
@merchantm The best way to install the current version of landsat-util is to use the brew formula.

We are working on a new version that has almost no outside dependencies that purely work with python-based libraries. We are expecting to release this version very soon. Stay tuned.

**Comment by merchantm** [comment]
Thanks Scisco, brew didn't work for me. Do you have any thoughts around when your new package will be available & what will be included. Thanks

**Comment by merchantm** [comment]
Hi Scisco,

Based on your last comment, I installed using brew. I got it to download images. 
When processing, I run into this error:

convert: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/857.
Starting the image processing
global name 'cv2' is not defined
Skipping Image Correction using OpenCV
Convertin image tweaks
Convert: averaging
RuntimeError: module compiled against API version 9 but this version of numpy is 6
RuntimeError: module compiled against API version 9 but this version of numpy is 6
Traceback (most recent call last):
  File "/usr/local/bin/gdal_calc.py", line 50, in <module>
    from gdalnumeric import *
  File "/usr/local/Cellar/landsat-util/0.2.0/libexec/lib/python2.7/site-packages/GDAL-1.11.0-py2.7-macosx-10.9-intel.egg/gdalnumeric.py", line 5, in <module>
    from osgeo.gdal_array import *
  File "/usr/local/Cellar/landsat-util/0.2.0/libexec/lib/python2.7/site-packages/GDAL-1.11.0-py2.7-macosx-10.9-intel.egg/osgeo/gdal_array.py", line 25, in <module>
    _gdal_array = swig_import_helper()
  File "/usr/local/Cellar/landsat-util/0.2.0/libexec/lib/python2.7/site-packages/GDAL-1.11.0-py2.7-macosx-10.9-intel.egg/osgeo/gdal_array.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal_array', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import
subprocess.CalledProcessError: Command '['gdal_calc.py', '-A', '/var/folders/11/gkx1793x1tdg0tm2r7xx816r0000gn/T/tmpvaMT2_/LC80220392014003LGN00/warp/LC80220392014003LGN00_B2.TIF', '--outfile=/var/folders/11/gkx1793x1tdg0tm2r7xx816r0000gn/T/tmpvaMT2_/LC80220392014003LGN00/final/band-mask.TIF', '--calc=1*(A>0)', '--type=UInt16']' returned non-zero exit status 1

Let me know if you have any suggestions.

Thanks

**Comment by scisco** [comment]
@MYM2107 we have released a new version of landsat-util that resolves some of the gdal dependency issues. Please upgrade to this version and let me know if you still have this issue. To upgrade run:

    $: pip install -U landsat-util
