### ISSUE TITLE
Images kind of grainy

### ISSUE THREAD

**Issue by ddd1600** [developmentseed/landsat-util#35]
I'm not sure if this is a valid "issue", but is there any way to get higher resolution imagery than this? Google has imagery that has at least 3 times as much resolution as this.

What is this, by the way, 2 meter resolution? What is the resolution of this imagery?

**Comment by scisco** [comment]
@ddd1600 I'm afraid not.

You can read more about Landsat 8 [here](http://en.wikipedia.org/wiki/Landsat_8).

This part of the article relates to your questions:

> Providing moderate-resolution imagery, from 15 meters to 100 meters, of Earth’s land surface and polar regions, Landsat 8 will operate in the visible, near-infrared, short wave infrared, and thermal infrared spectrums. Landsat 8 will capture approximately 400 scenes a day
