### ISSUE TITLE
Processed "final.TIF" images are not georeferenced (as warned by error messages when processing)

### ISSUE THREAD

**Issue by ddd1600** [developmentseed/landsat-util#36]
My final.TIF images are not openable with Google Earth Pro or any other program which loads georeferenced TIF (raster) images into a coordinate reference system. I'm seeing in the output when I run the `process` command that there are certain attributes that are not being transposed to the final output. I assume this is it. I'm running this process from Ubuntu on a VirtualBox, everything has been installed through apt-get.

So, I just ran this command:

david:~$ landsat process LC80160362015028LGN00.tar.bz

and got this output from the command line:

/tmp/tmpJenmEl/LC80160362015028LGN00 folder created
/tmp/tmpJenmEl/LC80160362015028LGN00/warp folder created
/tmp/tmpJenmEl/LC80160362015028LGN00/scaled folder created
/tmp/tmpJenmEl/LC80160362015028LGN00/final folder created
/home/david/landsat/processed/LC80160362015028LGN00 folder created
Unzipping LC80160362015028LGN00 - It might take some time
Creating output file that is 7715P x 7895L.
Processing input file /tmp/tmpJenmEl/LC80160362015028LGN00/LC80160362015028LGN00_B4.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7715P x 7895L.
Processing input file /tmp/tmpJenmEl/LC80160362015028LGN00/LC80160362015028LGN00_B3.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7715P x 7895L.
Processing input file /tmp/tmpJenmEl/LC80160362015028LGN00/LC80160362015028LGN00_B2.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 15428P x 15789L.
Processing input file /tmp/tmpJenmEl/LC80160362015028LGN00/LC80160362015028LGN00_B8.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Starting the Min/Max process with designated -percent cut- for band 4 of LC80160362015028LGN00
...
Finished processing band 4 of LC80160362015028LGN00
Starting the Min/Max process with designated -percent cut- for band 3 of LC80160362015028LGN00
...
Finished processing band 3 of LC80160362015028LGN00
Starting the Min/Max process with designated -percent cut- for band 2 of LC80160362015028LGN00
...
Finished processing band 2 of LC80160362015028LGN00
scaling pan to min max with 2% cut for band 4
Input file size is 7715, 7895
0...10...20...30...40...50...60...70...80...90...100 - done.
scaling pan to min max with 2% cut for band 3
Input file size is 7715, 7895
0...10...20...30...40...50...60...70...80...90...100 - done.
scaling pan to min max with 2% cut for band 2
Input file size is 7715, 7895
0...10...20...30...40...50...60...70...80...90...100 - done.
/tmp/tmpJenmEl/LC80160362015028LGN00/warp/LC80160362015028LGN00_B4.TIF[0] TIFF 7715x7895 7715x7895+0+0 16-bit Grayscale DirectClass 121.9MB 1.410u 0:02.759
/tmp/tmpJenmEl/LC80160362015028LGN00/warp/LC80160362015028LGN00_B3.TIF[0] TIFF 7715x7895 7715x7895+0+0 16-bit Grayscale DirectClass 121.9MB 1.140u 0:02.489
/tmp/tmpJenmEl/LC80160362015028LGN00/warp/LC80160362015028LGN00_B2.TIF[0] TIFF 7715x7895 7715x7895+0+0 16-bit Grayscale DirectClass 121.9MB 0.670u 0:01.799
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
/tmp/tmpJenmEl/LC80160362015028LGN00/scaled/LC80160362015028LGN00_B4.TIF[0] TIFF 7715x7895 7715x7895+0+0 8-bit Grayscale DirectClass 60.97MB 1.430u 0:01.700
/tmp/tmpJenmEl/LC80160362015028LGN00/scaled/LC80160362015028LGN00_B3.TIF[0] TIFF 7715x7895 7715x7895+0+0 8-bit Grayscale DirectClass 60.97MB 1.090u 0:01.260
/tmp/tmpJenmEl/LC80160362015028LGN00/scaled/LC80160362015028LGN00_B2.TIF[0] TIFF 7715x7895 7715x7895+0+0 8-bit Grayscale DirectClass 60.97MB 0.720u 0:00.850
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
Starting the image processing
Starting the image processing
Starting the image processing
Convertin image tweaks
Convert: averaging
/usr/bin/gdal_calc.py:266: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  myNDVs=1*numpy.logical_or(myNDVs==1, myval==myNDV[i])
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
Input file size is 7715, 7895
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 7715, 7895
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 7715, 7895
0...10...20...30...40...50...60...70...80...90...100 - done.
/usr/bin/gdal_calc.py:266: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  myNDVs=1*numpy.logical_or(myNDVs==1, myval==myNDV[i])
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
/usr/bin/gdal_calc.py:266: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  myNDVs=1*numpy.logical_or(myNDVs==1, myval==myNDV[i])
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
/usr/bin/gdal_calc.py:266: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  myNDVs=1*numpy.logical_or(myNDVs==1, myval==myNDV[i])
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
convert.im6: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
World file written to '/tmp/tmpJenmEl/LC80160362015028LGN00/warp/LC80160362015028LGN00_B4.tfw'.
The output is stored at /home/david/landsat/processed.

In the middle there you can see the errors that are likely causing this issue. Would appreciate any help you guys can give. Thanks

**Comment by ddd1600** [comment]
OK, let me make this a little easier. I can georeference these images myself. My best solution I think is to determine the exact coordinates of each of the four corners of each "final.TIF" image. How do I determine these coordinates?

**Comment by scisco** [comment]
@ddd1600 There are a number of ways to get the four corners. An easy way is to query development seed's API for landsat. Use the below URL and change the sceneID with your image sceneID:

http://api.developmentseed.org:8000/landsat?search=sceneID:LC80160362015028LGN00

The returned json file includes 8 fields that has the corners coordinates of the image such as:

- "lowerRightCornerLongitude": -78.93054,
- "lowerLeftCornerLatitude": 33.93558,
- "upperRightCornerLongitude": -78.42252,
- "lowerLeftCornerLongitude": -80.93539,
