### ISSUE TITLE
Installation error on Ubuntu 12.04LTS

### ISSUE THREAD

**Issue by rmm-san** [developmentseed/landsat-util#37]
I have tried to install landsat-util on Ubuntu 12.04lts, and I get the following on the pip-log:
/usr/bin/pip run on Wed Feb 11 15:50:49 2015
Downloading/unpacking python-pip
  Getting page http://pypi.python.org/simple/python-pip
  Could not fetch URL http://pypi.python.org/simple/python-pip: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/python-pip when looking for download links for python-pip
  Getting page http://pypi.python.org/simple/
  URLs to search for versions for python-pip:
  * http://pypi.python.org/simple/python-pip/
  Getting page http://pypi.python.org/simple/python-pip/
  Could not fetch URL http://pypi.python.org/simple/python-pip/: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/python-pip/ when looking for download links for python-pip
  Could not find any downloads that satisfy the requirement python-pip
No distributions at all found for python-pip
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 948, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 152, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for python-pip

**Comment by scisco** [comment]
@rmm-san Ubuntu 12 installation is quite challenging. 

Either use our [travis recipe](https://github.com/developmentseed/landsat-util/blob/master/.travis.yml) or [Vagrantfile](https://github.com/developmentseed/landsat-util/blob/master/Vagrantfile) as a guide.

Let me know if this helps.
