### ISSUE TITLE
No matches found/GEOS Error

### ISSUE THREAD

**Issue by FabianVista** [developmentseed/landsat-util#38]
Hi, thanks for this great tool, thats what I've been looking for for a while now. Downloading with scene ID works fine, but searching gives me some errors:
For example the search with "landsat search --cloud 4 --start "january 1 2014" --end "december 10 2014" pr 192 023" delivers "No matches found"
The same search with the parameter country germany results in "ERROR 6: GEOS support not enabled" as does the search with shape files.

I appreciate any help!

**Comment by scisco** [comment]
@FabianVista We just released a new version of landsat-util that resolves some of the issues.

On your first question, it seems that there are no images with cloud percentage of 4 in the given path and row for the dates you mentioned. 

If you increase your cloud percentage to 100, there are 20 scenes available in this area. Try this:

    $: landsat search --cloud=100 --start="january 1 2014" --end="december 10 2014" --pathrow=192,023

In the new version we have removed the ability to search from a shapefile. Instead, you can provide lat and long coordinates to find the images you look for.

**Comment by FabianVista** [comment]
Thanks for your help!
