### ISSUE TITLE
Error using command  sudo pip install -U git+git://github.com/developmentseed/landsat-util.git

### ISSUE THREAD

**Issue by Rishabh-K** [developmentseed/landsat-util#43]
I am using the following command on ubuntu on digital ocean:
 sudo pip install -U git+git://github.com/developmentseed/landsat-util.git

But this is giving the following error:::::
ERROR>>>
pip can't proceed with requirement 'GDAL==1.11.0 (from landsat==0.2.0)' due to a pre-existing build directory.
 location: /tmp/pip_build_root/GDAL
This is likely due to a previous installation that failed.
pip is being responsible and not assuming it can delete this.
Please delete it and try again.

Storing debug log for failure in /root/.pip/pip.log

**Comment by scisco** [comment]
@Rishabh-K We just released a new version of landsat that has resolved some of the dependencies issues.

Try running this command and let me know how it goes: `pip install -U landsat-util`
