### ISSUE TITLE
About command without list

### ISSUE THREAD

**Issue by Rishabh-K** [developmentseed/landsat-util#45]
python download_landsat_scene.py -o scene -b LC8 -d 20130127 -s 181025 -u usgs.txt --output /landsat/image

I ran the following command that downloaded 28GB zip files. Now how can I find that this data is latest.
And is this the full data?

**Comment by kamicut** [comment]
I'm not sure what the script you ran does. Landsat scene names follow a convention where the first 6 digits after LC8 are the location, the next 4 are the year, and then the next 3 are the day in the year.

For example LC80390222013076EDC00 is 2013, day 076 at location 039/022

For more information: http://landsat.usgs.gov/naming_conventions_scene_identifiers.php
