### ISSUE TITLE
Feature Request: Landsat image of a bounding box

### ISSUE THREAD

**Issue by llimllib** [developmentseed/landsat-util#62]
At one point, I tried to use landsat-util to automatically generate landsat images of given bounding boxes, and I got totally stranded trying to deal with coordinate transforms.

Would be awesome if I could just say `landsat-util process <path> --crop <bbox>`. Or is that super easy to do with some magic gdal command, or some such?

**Comment by kamicut** [comment]
@llimllib Do you mean process multiple images within a bounding box and crop them to a particular shape or crop one scene using a provided shape?

**Comment by llimllib** [comment]
It seems to me like it's outside the scope of landsat-util to join multiple images inside a bounding box, which adds all kinds of complications.

I just mean, if you said `landsat-util process <path> --crop <bbox>`, the output would be the intersection of the tiff represented by <path> and <bbox>. Even better if you don't have to spend processing time on the parts of the image outside that intersection, but cropping after the process would still be useful (IMO).

**Comment by drewbo** [comment]
@llimllib I added this to a [new branch](https://github.com/developmentseed/landsat-util/tree/feature-62_bounding_box) if you want to take a look. Bounding box is given as four separate arguments (min lon, min lat, max lon, max lat) and crops the image before color correction.

**Comment by llimllib** [comment]
Thank you, that's awesome, I hope to get a chance to try it out this weekend.

**Comment by njwilson23** [comment]
Is this fixed by 4776fa90af7b592cea169bac6ce059ca53d4f854?

**Comment by llimllib** [comment]
I think definitely, I didn't close this because I didn't know if those patches ever landed

**Comment by scisco** [comment]
yes this is added. You can use the `--clip` option. Example is here: https://pythonhosted.org/landsat-util/overview.html#image-processing
