### ISSUE TITLE
Fails on systems where /usr/bin/python is Python 3

### ISSUE THREAD

**Issue by kannes** [developmentseed/landsat-util#65]
On Archlinux /usr/bin/python is actually Python 3 but landsat-util seems to only work in Python 2.
I have no idea if it is possible to specify the actual (major) version of Python a script should use, but if you can, it would be great.

**Comment by kannes** [comment]
The error message is this, in case others wonder and find this via Google:

```Traceback (most recent call last):
  File "/usr/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/usr/lib/python3.4/site-packages/landsat/__init__.py", line 1, in <module>
    import settings
ImportError: No module named 'settings'```

**Comment by kamicut** [comment]
@kannes I haven't tested landsat-util using Python 3, but @scisco might have an idea about this error. You can [make a virtual environment](http://stackoverflow.com/questions/1534210/use-different-python-version-with-virtualenv) that uses python 2. You can then install the tool using that virtual environment.

**Comment by ajnisbet** [comment]
Linux distros [should](https://www.python.org/dev/peps/pep-0394/) support the `/usr/bin/python2` binary

**Comment by scisco** [comment]
We don't support python 3 yet but a PR should arrive soon
