### ISSUE TITLE
Colour & contrast correction 

### ISSUE THREAD

**Issue by nassosstylianou** [developmentseed/landsat-util#66]
Finding that some scenes returning results that are really dark after processing and pansharpening.
Two examples attached.
SceneIDs:
LC81950292014015LGN00
LC81760362014250LGN00
![lc81950292014015lgn00](https://cloud.githubusercontent.com/assets/5431776/6986660/5f68a6e4-da37-11e4-89fb-cc875d726a85.png)
![lc81760362014250lgn00](https://cloud.githubusercontent.com/assets/5431776/6986662/60de9f6a-da37-11e4-9e27-3ddfc17bfe12.png)

**Comment by scisco** [comment]
@drewbo I did some playing around with the new image processing in version 0.6.

If realized if we change the lower percentage limit form 0.1 to 0, the produced images are considerably less darker and more colorful. Below are a few scenes produced with this change:

`band = self._color_correction(band, self.bands[i], 0, cloud_cover)`

LC81950292014015LGN00
![screen shot 2015-04-24 at 6 35 47 pm](https://cloud.githubusercontent.com/assets/1933118/7329741/c3f2e7b2-eab0-11e4-9573-8e3ec3fbaef9.png)

LC81760362014250LGN00
![screen shot 2015-04-24 at 6 38 07 pm](https://cloud.githubusercontent.com/assets/1933118/7329761/138b94ea-eab1-11e4-9fd2-ef75c278810d.png)

LC80130312015071LGN00
![screen shot 2015-04-24 at 6 39 45 pm](https://cloud.githubusercontent.com/assets/1933118/7329780/5868257e-eab1-11e4-8d9d-2b62067083a1.png)

LC80130312014276LGN00
![screen shot 2015-04-24 at 6 39 59 pm](https://cloud.githubusercontent.com/assets/1933118/7329782/5d275490-eab1-11e4-9986-8b48c2500bfd.png)

I ran image processes for a number of scenes across the globe (different times, different latitudes and different cloud covers) and all produced nice images. 

What do you think?

**Comment by jacquestardie** [comment]
Some of the feedback we've gotten re: http://snapsat.org/ has been that the color contrast for cloud-heavy scenes has been off.

Here's what that `LC80130312014276LGN00` you posted looks like produced with the current settings:

![](http://snapsatpreviews.s3.amazonaws.com/pre_LC80130312014276LGN00_bands_432.png)

Your update seems like a serious update in this case at least.
