### ISSUE TITLE
download band 8 in continuous download/process/pansharpen command

### ISSUE THREAD

**Issue by scisco** [developmentseed/landsat-util#73]
This command `landsat download LC81410412015088LGN00 --bands 432 -p --pansharpen` fails because band 8 is not downloaded from aws.

Have to make sure that band 8 is downloaded if pansharpen flag is used for 2015 and newer imagery.

**Comment by jacquestardie** [comment]
If you don't mind me asking, why isn't Band 8 downloaded from the AWS dataset?

**Comment by scisco** [comment]
@jacquestardie It is essentially a bug. Will fix in the next update.

**Comment by jacquestardie** [comment]
:+1:

**Comment by emiliano-melchiori** [comment]
I have an issue with the optional argument --bands or -band. It is not working for any combination and it downloads the entire tar.bz with the 11 bands.
I have tried landsat download LC82210742014277LGN00 --bands 432 and landsat download LC82210742014277LGN00 --bands 7 with the same result
Thanks in advance

**Comment by scisco** [comment]
@emiliano-melchiori Unfortunately images before January 2015 are only available in tar format. Only images after this date are available unzipped via AWS. Hence `--bands` doesn't really work with scenes that are from 2014 or before.

You can read more about it here: https://developmentseed.org/blog/2015/03/19/aws-landsat-archive/

From the article:

> Our newest releases of Libra and landsat-util utilize Landsat on AWS for 2015 imagery. Landsat on AWS provides 2015 imagery as unzipped individual bands. AWS makes this imagery available extremely quickly, often within hours of capture. We can pull only the data that we need and to work with it immediately.

**Comment by emiliano-melchiori** [comment]
Thanks a lot for the answer. 
I have done a procedure to process the tar.gz file and extract the band of interest, but anyway the good thing would to download the selected bands instead of the entire package.
Congratulations for this tool. I will use it periodically in my work.
One more question. Do you know how much time requires for a recently acquired image to be available for download?

**Comment by emiliano-melchiori** [comment]
sorry... didn't fully read the doc!

**Comment by emiliano-melchiori** [comment]
Hi Scisco,

I cannot find the way to ask you other way, so I try this way.

Is there a way to download the BQA band with the landsat-util app without
downloading the entire package. I mean, which is the assignation value. I
have tried B10, B11 or B12, and they all go for B1! I supposed that it
would be 12.

Thanks






2015-05-21 14:08 GMT-03:00 Scisco <notifications@github.com>:

> @emiliano-melchiori <https://github.com/emiliano-melchiori> Unfortunately
> images before January 2015 are only available in tar format. Only images
> after this date are available unzipped via AWS. Hence --bands doesn't
> really work with scenes that are from 2014 or before.
>
> You can read more about it here:
> https://developmentseed.org/blog/2015/03/19/aws-landsat-archive/
>
> From the article:
>
> Our newest releases of Libra and landsat-util utilize Landsat on AWS for
> 2015 imagery. Landsat on AWS provides 2015 imagery as unzipped individual
> bands. AWS makes this imagery available extremely quickly, often within
> hours of capture. We can pull only the data that we need and to work with
> it immediately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developmentseed/landsat-util/issues/73#issuecomment-104357836>
> .
>



-- 
Emiliano Melchiori
