### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by bucricket** [developmentseed/landsat-util#77]
Its probably a simple fix but I'm not an IT guy.  I keep getting the following error

landsat search --cloud 4 --start "january 1 2014" --end "january 10 2014" -p 009,045
Traceback (most recent call last):
  File "/Users/schull/anaconda/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/Users/schull/anaconda/lib/python2.7/site-packages/landsat/landsat.py", line 21, in <module>
    from image import Process, FileDoesNotExist
  File "/Users/schull/anaconda/lib/python2.7/site-packages/landsat/image.py", line 13, in <module>
    import rasterio
  File "/Users/schull/anaconda/lib/python2.7/site-packages/rasterio/__init__.py", line 8, in <module>
    from rasterio._base import eval_window, window_shape, window_index
ImportError: dlopen(/Users/schull/anaconda/lib/python2.7/site-packages/rasterio/_base.so, 2): Library not loaded: libgdal.1.dylib
  Referenced from: /Users/schull/anaconda/lib/python2.7/site-packages/rasterio/_base.so
  Reason: image not found

Any ideas how to fix it?

**Comment by scisco** [comment]
@bucricket It seems that landsat-util is not properly installed. The command you are running should do a simple search. I'm not sure why the image processing library is called.

Do you get an error when you run: `landsat -h`?

**Comment by bucricket** [comment]
yes I get the following error.

landsat -h
Traceback (most recent call last):
  File "/Users/schull/anaconda/bin/landsat", line 5, in <module>
    import landsat.landsat
  File "/Users/schull/anaconda/lib/python2.7/site-packages/landsat/landsat.py", line 21, in <module>
    from image import Process, FileDoesNotExist
  File "/Users/schull/anaconda/lib/python2.7/site-packages/landsat/image.py", line 13, in <module>
    import rasterio
  File "/Users/schull/anaconda/lib/python2.7/site-packages/rasterio/__init__.py", line 8, in <module>
    from rasterio._base import eval_window, window_shape, window_index
ImportError: dlopen(/Users/schull/anaconda/lib/python2.7/site-packages/rasterio/_base.so, 2): Library not loaded: libgdal.1.dylib
  Referenced from: /Users/schull/anaconda/lib/python2.7/site-packages/rasterio/_base.so
  Reason: image not found

Mitch

**Comment by scisco** [comment]
@bucricket My guess was correct. You have an installation issue. I think `rasterio` is having problem finding a GDAL library called `libgdal.1.dylib`.

Do you have GDAL installed? This ticket discusses a similar issue: https://github.com/mapbox/rasterio/issues/103

An easy work around for you could be running `conda install gdal`

**Comment by bucricket** [comment]
I already have gdal installed.  I guess raster doesn’t know where to look.

**Comment by kashingtonDC** [comment]
Any word on this fix? Having the same issue

**Comment by bucricket** [comment]
No luck so far.  It's unfortunate it would be so useful.

Mitch

**Comment by kashingtonDC** [comment]
I fixed this by using: 
conda install gdal 
conda install rasterio 
pip install rasterio

**Comment by bucricket** [comment]
You are my hero!  It works!

Mitch

**Comment by bucricket** [comment]
Hi,

Have you been able to use the module’s?

for example

from landsat.search import Search

search = Search()
search.search('003,003', '2014-01-01', '2014-06-01’)

I get the following

{'code': u'SERVER_ERROR',
'message': u'Check your request and try again',
'status': u'error’}


Mitch

**Comment by bucricket** [comment]
Hi,

I finally got landsat-util to work for the command line.  I want to use the modules now in my code.

I can’t seem to get it work.

for example

from landsat.search import Search

search = Search()
search.search('003,003', '2014-01-01', '2014-06-01’)

I get the following

{'code': u'SERVER_ERROR',
'message': u'Check your request and try again',
'status': u'error’}

yet it works on the command line.

Mitch

**Comment by kashingtonDC** [comment]
I haven't tried to use it in a script. I actually switched over from landsat-util to the LANDSAT-Download package (https://github.com/olivierhagolle/LANDSAT-Download) because it seems to be more friendly with windows command line and python 3.4. I could only get landsat-util to work on python 2.7. I'll let you know once I've tried incorporating the modules in to a py script, which will be happening quite soon. In the mean time, good luck!

**Comment by bucricket** [comment]
@scisco Do you have any idea why I can't use the modules in a python script? 

I finally got landsat-util to work for the command line.  I want to use the modules now in my code.

I can’t seem to get it work.

for example

from landsat.search import Search

search = Search()
search.search('003,003', '2014-01-01', '2014-06-01’)

I get the following

{'code': u'SERVER_ERROR',
'message': u'Check your request and try again',
'status': u'error’}

yet it works on the command line.

Mitch

**Comment by scisco** [comment]
@bucricket 

Try this:

```python
from landsat.search import Search

search = Search()
print search.search('003,003', start_date='2014-01-01', end_date='2014-06-01')

```

**Comment by bucricket** [comment]
Great!  That seems to have worked. So do you have an example for downloading the data too?  It would be great if there were examples for all the modules but at the moment I really need to download the data.  

This is awesome by the way.

Mitch

**Comment by scisco** [comment]
I haven't tested this, but it should work:

```python
from landsat.downloader import Downloader

d = Downloader(download_dir='/path/to/directory')
print d.download(['scened1', 'scened2'], ['4', '3', '2'])
```

**Comment by bucricket** [comment]
Great! 

That seems to work!

Mitch

**Comment by bucricket** [comment]
Hi,

One more thing that I can’t quite get to work.  The downloader always downloads all the files even if I give it bands for a subset list.  Have you encounter this?

Mitch

**Comment by scisco** [comment]
Only scenes from 2015 are available on AWS and can be downloaded as separate bands

**Comment by bucricket** [comment]
Ok….I can see that when I download 2014 data it downloads all bands and in 2015 it downloads only the bands I want.

**Comment by scisco** [comment]
Glad it worked :+1:
