### ISSUE TITLE
selective band download does not always work and returns a tar of all bands

### ISSUE THREAD

**Issue by cappelaere** [developmentseed/landsat-util#87]
This one works fine: landsat download LC80420362015082LGN00 --bands 57
it downloads to a subfolder B5,B7,MTL as expected

This one does not: landsat download LC80420362013108LGN01 --bands 57
it downloads a tar.bz with all bands

**Comment by jflasher** [comment]
Hi @cappelaere, this is because only scenes after 2015 are available from AWS which offers individual bands.

**Comment by cappelaere** [comment]
Hi John,

Did I miss this in documentation?  I got blindsided… using it in an automated manner...
It is always problematic when an API does not return the same thing in same format.
May be it could untar the file and delete the ones you did not ask for?

I guess I can do this on my side as well.  Not a big deal.
Many Thanks.

Pat Cappelaere
pat@cappelaere.com

Cell: 410 340 4868
Skype: patrice_cappelaere
gmail: cappelaere@gmail.com

**Comment by jflasher** [comment]
I've opened up a new issue to capture adding a callout to the docs and will close this for now. We can look at other ways to handle this in the future.
