### ISSUE TITLE
Ubuntu 14.04 

### ISSUE THREAD

**Issue by northrivergeo** [developmentseed/landsat-util#9]
Lemme see how much I can post and have this make sense. 
I use ubuntugis-unstable
1. landsat download LC80200362014197LGN00
2. landsat process ./zip/LC80200362014197LGN00.tar.bz

Output: 
/tmp/tmpZkN3ao/LC80200362014197LGN00 folder created
/tmp/tmpZkN3ao/LC80200362014197LGN00/warp folder created
/tmp/tmpZkN3ao/LC80200362014197LGN00/scaled folder created
/tmp/tmpZkN3ao/LC80200362014197LGN00/final folder created
Unzipping LC80200362014197LGN00 - It might take some time
Creating output file that is 7720P x 7893L.
Processing input file /tmp/tmpZkN3ao/LC80200362014197LGN00/LC80200362014197LGN00_B4.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7720P x 7893L.
Processing input file /tmp/tmpZkN3ao/LC80200362014197LGN00/LC80200362014197LGN00_B3.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 7720P x 7893L.
Processing input file /tmp/tmpZkN3ao/LC80200362014197LGN00/LC80200362014197LGN00_B2.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Creating output file that is 15439P x 15786L.
Processing input file /tmp/tmpZkN3ao/LC80200362014197LGN00/LC80200362014197LGN00_B8.TIF.
0...10...20...30...40...50...60...70...80...90...100 - done.
Starting the Min/Max process with designated -percent cut- for band 4 of LC80200362014197LGN00
...
Finished processing band 4 of LC80200362014197LGN00
Starting the Min/Max process with designated -percent cut- for band 3 of LC80200362014197LGN00
...
Finished processing band 3 of LC80200362014197LGN00
Starting the Min/Max process with designated -percent cut- for band 2 of LC80200362014197LGN00
...
Finished processing band 2 of LC80200362014197LGN00
scaling pan to min max with 2% cut for band 4
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
scaling pan to min max with 2% cut for band 3
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
scaling pan to min max with 2% cut for band 2
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
/tmp/tmpZkN3ao/LC80200362014197LGN00/warp/LC80200362014197LGN00_B4.TIF[0] TIFF 7720x7893 7720x7893+0+0 16-bit Grayscale DirectClass 121.9MB 1.890u 0:01.919
/tmp/tmpZkN3ao/LC80200362014197LGN00/warp/LC80200362014197LGN00_B3.TIF[0] TIFF 7720x7893 7720x7893+0+0 16-bit Grayscale DirectClass 121.9MB 1.300u 0:01.300
/tmp/tmpZkN3ao/LC80200362014197LGN00/warp/LC80200362014197LGN00_B2.TIF[0] TIFF 7720x7893 7720x7893+0+0 16-bit Grayscale DirectClass 121.9MB 0.720u 0:00.719
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
/tmp/tmpZkN3ao/LC80200362014197LGN00/scaled/LC80200362014197LGN00_B4.TIF[0] TIFF 7720x7893 7720x7893+0+0 8-bit Grayscale DirectClass 61MB 1.860u 0:01.889
/tmp/tmpZkN3ao/LC80200362014197LGN00/scaled/LC80200362014197LGN00_B3.TIF[0] TIFF 7720x7893 7720x7893+0+0 8-bit Grayscale DirectClass 61MB 1.240u 0:01.259
/tmp/tmpZkN3ao/LC80200362014197LGN00/scaled/LC80200362014197LGN00_B2.TIF[0] TIFF 7720x7893 7720x7893+0+0 8-bit Grayscale DirectClass 61MB 0.650u 0:00.649
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 33922 (0x8482) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
convert.im6: Unknown field with tag 34737 (0x87b1) encountered.`TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
Starting the image processing
global name 'cv2' is not defined
Skipping Image Correction using OpenCV
Convertin image tweaks
Convert: averaging
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 7720, 7893
0...10...20...30...40...50...60...70...80...90...100 - done.
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
0 .. 10 .. 20 .. 30 .. 40 .. 50 .. 60 .. 70 .. 80 .. 90 .. 100 - Done
convert.im6: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/768.
OSError: [Errno 2] No such file or directory

**Comment by Abdel-razek** [comment]
I am getting the exact same error on Ubuntu 14.04. Tried already the solution you suggested (sudo apt-get install imagemagick geotiff-bin), but still getting the error

any new development?
