### ISSUE TITLE
B10,B11,BQA bands download

### ISSUE THREAD

**Issue by emiliano-melchiori** [developmentseed/landsat-util#90]
I've seem to find a complication when trying to download the QA band. Also with bands 10 and 11 of 2015.
It seems that the function convert_to_integer_list() is not considering two digits integers, or vocals in the sequence.
If 10 or 11 is specified, B1 will be downloaded. If anything else is written, the entire package is downloaded.

**Comment by JorgeGT** [comment]
I've been able to download band 10 if specified as `--band 10,7,3`. Also, I've processed them with the same option:

```
$ landsat process landsat/downloads/LC81990332014251LGN00 -b 10,7,3
* Image processing started for bands 10-7-3
===> Getting boundaries
===> Projecting
     band 10
     band 7
     band 3
===> Final Steps
     Color correcting band 10
     Color correcting band 7
     Color correcting band 3
     Writing to file
===> The output is stored at /whatever
===> Done!
Time spent : 57.05 seconds
```

However the program doesn't seem to consider a way to download or process individual TIRS bands, not to speak of the QA band:

```
$ landsat process landsat/downloads/LC81990332015014LGN00 -b 10
LC81990332015014LGN00_B0.* does not exist
Time spent : 0.01 seconds

$ landsat process landsat/downloads/LC81990332015014LGN00 -b '10'
LC81990332015014LGN00_B0.* does not exist
Time spent : 0.01 seconds
```

I think support for these bands would be rather nice! =)

**Comment by emiliano-melchiori** [comment]
I have a different behaviour here (Brazil) when trying to download B10 individually.
$ landsat download LC82210672015120LGN00 -b 10
===> Downloading: LC82210672015120LGN00_B1.TIF

Instead of B0, which doesn't exists, it gets B1. I suppose because of the method that is being used to decode the band. It gets only one char if it doesn't find a comma.

For me, the BQA band is of much importance, so I have modified the code to include in the download request every time I need to download an image band. So right now I have nothing to complain. It is just for the record and to develop a better tool.

**Comment by scisco** [comment]
@emiliano-melchiori @JorgeGT confirm this is not supported. I'll put it on the list to be fixed in the next release. Thanks for reporting.
