### ISSUE TITLE
Problem with pansharpening

### ISSUE THREAD

**Issue by Ocirne94** [developmentseed/landsat-util#93]
Hi,
I get some weird results with pansharpening.
After download of the image with landsat download, command
$ landsat process --bands 432 --pansharpen LC81950282014159LGN00
yields a strange image with messy colors; I attach an 1:1 crop.
landsat version 0.7.0 on Ubuntu 14.04.

![lc81950282014159lgn00_bands_432_pan_crop](https://cloud.githubusercontent.com/assets/11635321/8272284/b58b8d0a-183c-11e5-8534-10b33838ed9a.jpg)

**Comment by JorgeGT** [comment]
While the situation has improved with the recent merge, I'm still having some problems with pansharpening. The results have gone from something like this:

![captura de pantalla 2015-09-30 16 39 08](https://cloud.githubusercontent.com/assets/1165351/10196194/f27017f0-6791-11e5-9caf-113e3d0de970.png)

To something this (note the white regions where there should be data, probably it's better if you open the figures in new tabs):

![captura de pantalla 2015-09-30 16 39 16](https://cloud.githubusercontent.com/assets/1165351/10196199/f766e676-6791-11e5-93a9-e23703ceeaf7.png)

Compare with the same image without the `--pansharpening` option:

![captura de pantalla 2015-09-30 16 39 27](https://cloud.githubusercontent.com/assets/1165351/10196200/fb4dbcec-6791-11e5-8753-faaa2e1ff490.png)

Scene is `LC81990332015158LGN00`. I don't know if this is related to this bug, to the color stretching bug or a separate one, so I will post it there or as a separate one if you prefer :)
