### ISSUE TITLE
Documentation for pansharpening / processing within Python?

### ISSUE THREAD

**Issue by petulla** [developmentseed/landsat-util#98]
Hi
The docs don't give details for how to process or sharpen images within Python -- only for command line utils. 

Can the Python package perform image processing within a Python script?

**Comment by scisco** [comment]
@petulla You are right. The documentation only provides examples for how to use the CLI. We have to improve this. Here is a quick example for using pansharpening of the image processing class:

```python
from landsat.image import Process

p = Process(path='/path/to/image/image.TIF', bands=[4, 3, 2], dst_path='/path/to/dst/folder', verbose=False, force_unzip=False)

p.run(pansharpen=True)
```

The above script assumes that landsat-util is successfully installed and added to you python path.

Also, note that we are releasing an update to landsat-util that will change how the image processing class is structured. After the update the above code will work differently. I'll post an update here.
